### PR TITLE
Merging K8s_pod_separation feature branch to kubernetes

### PR DESCRIPTION
**Pull request by suvratjoshi**
This PR is created for merging feature branch K8s_pod_separation to kubernetes branch.

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

### CODE REVIEW

**Review by vaibhavparatwar — APPROVED** [review]

**Review by knekrasov — APPROVED** [review]

**Comment by suvratjoshi** [comment]
For testing this feature branch build was created :
http://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/centos-7.9/job/cortx-all-image-custom-ci/1590/

Testing using regular way of deployment is passed :
```
[root@ssc-vm-g2-rhev4-2610 k8_cortx_cloud]# kubectl get pods
NAME                                                   READY   STATUS    RESTARTS   AGE
consul-bszm6                                           1/1     Running   0          30m
consul-fsfnq                                           1/1     Running   0          30m
consul-ls8nb                                           1/1     Running   0          30m
consul-server-0                                        1/1     Running   0          30m
consul-server-1                                        1/1     Running   0          30m
consul-server-2                                        1/1     Running   0          30m
cortx-control-pod-794554988f-rtlrz                     4/4     Running   0          28m
cortx-data-pod-ssc-vm-g2-rhev4-2610-7c7878c98-9wsg4    9/9     Running   0          26m
cortx-data-pod-ssc-vm-g2-rhev4-2611-8c676cdf7-bkct4    9/9     Running   0          26m
cortx-data-pod-ssc-vm-g2-rhev4-2621-5589cdc864-d6f22   9/9     Running   0          26m
kafka-0                                                1/1     Running   0          29m
kafka-1                                                1/1     Running   0          29m
kafka-2                                                1/1     Running   0          29m
openldap-0                                             1/1     Running   0          30m
openldap-1                                             1/1     Running   0          30m
openldap-2                                             1/1     Running   0          30m
zookeeper-0                                            1/1     Running   0          29m
zookeeper-1                                            1/1     Running   0          29m
zookeeper-2                                            1/1     Running   0          29m
[root@ssc-vm-g2-rhev4-2610 k8_cortx_cloud]#
```
```
[root@ssc-vm-g2-rhev4-2610 k8_cortx_cloud]# kubectl exec -it cortx-data-pod-ssc-vm-g2-rhev4-2610-7c7878c98-9wsg4 -c cortx-motr-hax -- bash
[root@cortx-data-headless-svc-ssc-vm-g2-rhev4-2610 /]# hctl status
Data pool:
    # fid name
    0x6f00000000000001:0x81 'storage-set-1__sns'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0xcc 'Profile_the_pool': 'storage-set-1__sns' 'storage-set-1__dix' None
Services:
    cortx-data-headless-svc-ssc-vm-g2-rhev4-2621  (RC)
    [started]  hax        0x7200000000000001:0x31  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2621@2001
    [started]  ioservice  0x7200000000000001:0x34  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2621@3001
    [started]  ioservice  0x7200000000000001:0x41  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2621@3002
    [started]  confd      0x7200000000000001:0x4e  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2621@3003
    [started]  s3server   0x7200000000000001:0x51  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2621@4001
    [started]  s3server   0x7200000000000001:0x54  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2621@4002
    cortx-data-headless-svc-ssc-vm-g2-rhev4-2611
    [started]  hax        0x7200000000000001:0x7   inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2611@2001
    [started]  ioservice  0x7200000000000001:0xa   inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2611@3001
    [started]  ioservice  0x7200000000000001:0x17  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2611@3002
    [started]  confd      0x7200000000000001:0x24  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2611@3003
    [started]  s3server   0x7200000000000001:0x27  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2611@4001
    [started]  s3server   0x7200000000000001:0x2a  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2611@4002
    cortx-data-headless-svc-ssc-vm-g2-rhev4-2610
    [started]  hax        0x7200000000000001:0x5b  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2610@2001
    [started]  ioservice  0x7200000000000001:0x5e  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2610@3001
    [started]  ioservice  0x7200000000000001:0x6b  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2610@3002
    [started]  confd      0x7200000000000001:0x78  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2610@3003
    [started]  s3server   0x7200000000000001:0x7b  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2610@4001
    [started]  s3server   0x7200000000000001:0x7e  inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2610@4002
[root@cortx-data-headless-svc-ssc-vm-g2-rhev4-2610 /]#
```

**Comment by suvratjoshi** [comment]
For http://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/centos-7.9/job/cortx-all-image-custom-ci/1590/
Testing in pod separation way was also tested on three node setup :
```
NAME                            READY   STATUS    RESTARTS   AGE
consul-48hwh                    1/1     Running   0          13m
consul-bt7jw                    1/1     Running   0          13m
consul-jzmdt                    1/1     Running   0          13m
consul-server-0                 1/1     Running   0          13m
consul-server-1                 1/1     Running   0          13m
consul-server-2                 1/1     Running   0          13m
control-node-6cd84b9c8-snqgp    4/4     Running   0          12m
data-node1-697cbb7b8d-fq5bl     4/4     Running   0          10m
data-node2-787dd5c954-4j8kc     4/4     Running   0          10m
data-node3-85947c5854-x7r76     4/4     Running   0          10m
ha-node-799dd65756-q22vm        1/1     Running   0          11m
kafka-0                         1/1     Running   0          13m
kafka-1                         1/1     Running   0          13m
kafka-2                         1/1     Running   0          13m
server-node1-778ccfc4d4-pbktb   6/6     Running   0          8m18s
server-node2-6c88cdcfd-68vsk    6/6     Running   0          8m13s
server-node3-695bbdcf94-w4n26   6/6     Running   0          8m7s
symas-openldap-pod              1/1     Running   0          13m
zookeeper-0                     1/1     Running   0          13m
zookeeper-1                     1/1     Running   0          13m
zookeeper-2                     1/1     Running   0          13m
```
```
[root@ssc-vm-g2-rhev4-2466 ~]# kubectl exec -it data-node1-697cbb7b8d-fq5bl -c cortx-motr-hax -- /bin/bash
[root@data-node1 /]# hctl status
Data pool:
    # fid name
    0x6f00000000000001:0x90 'storage-set-1__sns'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0xdb 'Profile_the_pool': 'storage-set-1__sns' 'storage-set-1__dix' None
Services:
    data-node2
    [started]  hax        0x7200000000000001:0x2b  inet:tcp:data-node2@2001
    [started]  ioservice  0x7200000000000001:0x2e  inet:tcp:data-node2@3001
    [started]  ioservice  0x7200000000000001:0x3b  inet:tcp:data-node2@3002
    [started]  confd      0x7200000000000001:0x48  inet:tcp:data-node2@3003
    data-node1  (RC)
    [started]  hax        0x7200000000000001:0x7   inet:tcp:data-node1@2001
    [started]  ioservice  0x7200000000000001:0xa   inet:tcp:data-node1@3001
    [started]  ioservice  0x7200000000000001:0x17  inet:tcp:data-node1@3002
    [started]  confd      0x7200000000000001:0x24  inet:tcp:data-node1@3003
    data-node3
    [started]  hax        0x7200000000000001:0x4f  inet:tcp:data-node3@2001
    [started]  ioservice  0x7200000000000001:0x52  inet:tcp:data-node3@3001
    [started]  ioservice  0x7200000000000001:0x5f  inet:tcp:data-node3@3002
    [started]  confd      0x7200000000000001:0x6c  inet:tcp:data-node3@3003
    server-node1
    [started]  hax        0x7200000000000001:0x71  inet:tcp:server-node1@2001
    [started]  s3server   0x7200000000000001:0x74  inet:tcp:server-node1@4001
    [started]  s3server   0x7200000000000001:0x77  inet:tcp:server-node1@4002
    server-node2
    [started]  hax        0x7200000000000001:0x7c  inet:tcp:server-node2@2001
    [started]  s3server   0x7200000000000001:0x7f  inet:tcp:server-node2@4001
    [started]  s3server   0x7200000000000001:0x82  inet:tcp:server-node2@4002
    server-node3
    [started]  hax        0x7200000000000001:0x87  inet:tcp:server-node3@2001
    [started]  s3server   0x7200000000000001:0x8a  inet:tcp:server-node3@4001
    [started]  s3server   0x7200000000000001:0x8d  inet:tcp:server-node3@4002
[root@data-node1 /]#
```

**Comment by suvratjoshi** [comment]
Build : http://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/centos-7.9/job/cortx-all-image-custom-ci/1590/
9- node Jenkins deployment was also tested using Jenkins job :
http://eos-jenkins.colo.seagate.com/job/Cortx-kubernetes/job/deploy-cortx-k8-cluster/609/

```
[root@ssc-vm-g3-rhev4-2107 ~]# kubectl get pods
NAME                                                   READY   STATUS    RESTARTS   AGE
consul-5dpg9                                           1/1     Running   0          94m
consul-98lwt                                           1/1     Running   0          94m
consul-hkkvp                                           1/1     Running   0          94m
consul-k86f4                                           1/1     Running   0          94m
consul-kvdcs                                           1/1     Running   0          94m
consul-mgx2b                                           1/1     Running   0          94m
consul-mx6pd                                           1/1     Running   0          94m
consul-server-0                                        1/1     Running   0          94m
consul-server-1                                        1/1     Running   0          94m
consul-server-2                                        1/1     Running   0          94m
consul-vn6lh                                           1/1     Running   0          94m
consul-x6nrd                                           1/1     Running   0          94m
cortx-control-pod-67f8bb58bb-rskmf                     4/4     Running   0          90m
cortx-data-pod-ssc-vm-g3-rhev4-2107-7c886565d8-spfhk   9/9     Running   0          89m
cortx-data-pod-ssc-vm-g3-rhev4-2184-fd848d9c4-rkv47    9/9     Running   0          89m
cortx-data-pod-ssc-vm-g3-rhev4-2198-5f8d89df88-smxwh   9/9     Running   0          89m
cortx-data-pod-ssc-vm-g3-rhev4-2278-7c86894577-nfbvv   9/9     Running   0          89m
cortx-data-pod-ssc-vm-g3-rhev4-2279-6dc949f6cc-c6xss   9/9     Running   0          89m
cortx-data-pod-ssc-vm-g3-rhev4-2281-7948c87b8-n8x94    9/9     Running   0          89m
cortx-data-pod-ssc-vm-g3-rhev4-2282-5676cf688f-wrsg6   9/9     Running   0          88m
cortx-data-pod-ssc-vm-g3-rhev4-2283-56b86b8996-cbl7h   9/9     Running   0          88m
cortx-data-pod-ssc-vm-g3-rhev4-2284-7fb8d7fff9-ds99f   9/9     Running   0          88m
kafka-0                                                1/1     Running   0          93m
kafka-1                                                1/1     Running   0          93m
kafka-2                                                1/1     Running   0          93m
openldap-0                                             1/1     Running   0          94m
openldap-1                                             1/1     Running   0          94m
openldap-2                                             1/1     Running   0          94m
zookeeper-0                                            1/1     Running   0          93m
zookeeper-1                                            1/1     Running   0          93m
zookeeper-2                                            1/1     Running   0          93m
[root@ssc-vm-g3-rhev4-2107 ~]#
```
```
[root@ssc-vm-g3-rhev4-2107 ~]# kubectl exec -it cortx-data-pod-ssc-vm-g3-rhev4-2107-7c886565d8-spfhk -c cortx-motr-hax -- /bin/bash
[root@cortx-data-headless-svc-ssc-vm-g3-rhev4-2107 /]#
[root@cortx-data-headless-svc-ssc-vm-g3-rhev4-2107 /]#
[root@cortx-data-headless-svc-ssc-vm-g3-rhev4-2107 /]#
[root@cortx-data-headless-svc-ssc-vm-g3-rhev4-2107 /]# hctl status
Data pool:
    # fid name
    0x6f00000000000001:0x17d 'storage-set-1__sns'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0x246 'Profile_the_pool': 'storage-set-1__sns' 'storage-set-1__dix' None
Services:
    cortx-data-headless-svc-ssc-vm-g3-rhev4-2281  (RC)
    [started]  hax        0x7200000000000001:0x12d  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2281@2001
    [started]  ioservice  0x7200000000000001:0x130  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2281@3001
    [started]  ioservice  0x7200000000000001:0x13d  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2281@3002
    [started]  confd      0x7200000000000001:0x14a  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2281@3003
    [started]  s3server   0x7200000000000001:0x14d  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2281@4001
    [started]  s3server   0x7200000000000001:0x150  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2281@4002
    cortx-data-headless-svc-ssc-vm-g3-rhev4-2284
    [started]  hax        0x7200000000000001:0x157  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2284@2001
    [started]  ioservice  0x7200000000000001:0x15a  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2284@3001
    [started]  ioservice  0x7200000000000001:0x167  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2284@3002
    [started]  confd      0x7200000000000001:0x174  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2284@3003
    [started]  s3server   0x7200000000000001:0x177  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2284@4001
    [started]  s3server   0x7200000000000001:0x17a  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2284@4002
    cortx-data-headless-svc-ssc-vm-g3-rhev4-2279
    [started]  hax        0x7200000000000001:0x31  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2279@2001
    [started]  ioservice  0x7200000000000001:0x34  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2279@3001
    [started]  ioservice  0x7200000000000001:0x41  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2279@3002
    [started]  confd      0x7200000000000001:0x4e  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2279@3003
    [started]  s3server   0x7200000000000001:0x51  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2279@4001
    [started]  s3server   0x7200000000000001:0x54  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2279@4002
    cortx-data-headless-svc-ssc-vm-g3-rhev4-2107
    [started]  hax        0x7200000000000001:0x7   inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2107@2001
    [started]  ioservice  0x7200000000000001:0xa   inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2107@3001
    [started]  ioservice  0x7200000000000001:0x17  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2107@3002
    [started]  confd      0x7200000000000001:0x24  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2107@3003
    [started]  s3server   0x7200000000000001:0x27  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2107@4001
    [started]  s3server   0x7200000000000001:0x2a  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2107@4002
    cortx-data-headless-svc-ssc-vm-g3-rhev4-2282
    [started]  hax        0x7200000000000001:0x5b  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2282@2001
    [started]  ioservice  0x7200000000000001:0x5e  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2282@3001
    [started]  ioservice  0x7200000000000001:0x6b  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2282@3002
    [started]  confd      0x7200000000000001:0x78  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2282@3003
    [started]  s3server   0x7200000000000001:0x7b  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2282@4001
    [started]  s3server   0x7200000000000001:0x7e  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2282@4002
    cortx-data-headless-svc-ssc-vm-g3-rhev4-2198
    [started]  hax        0x7200000000000001:0x85  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2198@2001
    [started]  ioservice  0x7200000000000001:0x88  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2198@3001
    [started]  ioservice  0x7200000000000001:0x95  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2198@3002
    [started]  confd      0x7200000000000001:0xa2  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2198@3003
    [started]  s3server   0x7200000000000001:0xa5  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2198@4001
    [started]  s3server   0x7200000000000001:0xa8  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2198@4002
    cortx-data-headless-svc-ssc-vm-g3-rhev4-2184
    [started]  hax        0x7200000000000001:0xaf  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2184@2001
    [started]  ioservice  0x7200000000000001:0xb2  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2184@3001
    [started]  ioservice  0x7200000000000001:0xbf  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2184@3002
    [started]  confd      0x7200000000000001:0xcc  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2184@3003
    [started]  s3server   0x7200000000000001:0xcf  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2184@4001
    [started]  s3server   0x7200000000000001:0xd2  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2184@4002
    cortx-data-headless-svc-ssc-vm-g3-rhev4-2283
    [started]  hax        0x7200000000000001:0xd9  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2283@2001
    [started]  ioservice  0x7200000000000001:0xdc  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2283@3001
    [started]  ioservice  0x7200000000000001:0xe9  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2283@3002
    [started]  confd      0x7200000000000001:0xf6  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2283@3003
    [started]  s3server   0x7200000000000001:0xf9  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2283@4001
    [started]  s3server   0x7200000000000001:0xfc  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2283@4002
    cortx-data-headless-svc-ssc-vm-g3-rhev4-2278
    [started]  hax        0x7200000000000001:0x103  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2278@2001
    [started]  ioservice  0x7200000000000001:0x106  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2278@3001
    [started]  ioservice  0x7200000000000001:0x113  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2278@3002
    [started]  confd      0x7200000000000001:0x120  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2278@3003
    [started]  s3server   0x7200000000000001:0x123  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2278@4001
    [started]  s3server   0x7200000000000001:0x126  inet:tcp:cortx-data-headless-svc-ssc-vm-g3-rhev4-2278@4002
[root@cortx-data-headless-svc-ssc-vm-g3-rhev4-2107 /]#
```

**Comment by suvratjoshi** [comment]
image

**Comment by suvratjoshi** [comment]
image

**Review by SwapnilGaonkar7 — APPROVED** [review]

**Comment by suvratjoshi** [comment]
rerun premerge-test

**Comment by suvratjoshi** [comment]
The s3 IO was tested and and was successful on the 9 node  setup mentioned here.
```
[root@ssc-vm-g3-rhev4-2107 ~]# aws s3 mb s3://test
make_bucket: test
[root@ssc-vm-g3-rhev4-2107 ~]# aws s3 ls
2021-12-24 04:36:26 test
[root@ssc-vm-g3-rhev4-2107 ~]# aws s3 cp /etc/hosts s3://test
upload: ../etc/hosts to s3://test/hosts
[root@ssc-vm-g3-rhev4-2107 ~]# aws s3 cp /etc/hosts s3://test
upload: ../etc/hosts to s3://test/hosts
[root@ssc-vm-g3-rhev4-2107 ~]# aws s3 cp s3://test/hosts tanu
download: s3://test/hosts to ./tanu
[root@ssc-vm-g3-rhev4-2107 ~]# aws s3 ls s3://test
2021-12-24 05:03:46 204 hosts
[root@ssc-vm-g3-rhev4-2107 ~]#
```

**Comment by suvratjoshi** [comment]
Since all the testing is passed on the feature branch "K8s_pod_separation", we are good to merge it to kubernetes branch.

**Pull request merged**
