### PR TITLE
CORTX-29982: Incorrect list-item indent

### PR DESCRIPTION
**Pull request by hessio**
[CORTX-29982](https://jts.seagate.com/browse/CORTX-29982): Incorrect list-item indent

Solution:
Add 2 spaces at the start of the statements in documentation.

Signed-off-by: hessio <patrick.hession@seagate.com>

-----
[View rendered CODE_OF_CONDUCT.md](https://github.com/hessio/cortx-hare/blob/hessio-branch2/CODE_OF_CONDUCT.md)
[View rendered README.md](https://github.com/hessio/cortx-hare/blob/hessio-branch2/README.md)

### CODE REVIEW

**Comment by mssawant** [comment]
Hi @hessio, can you please reword the commit message as,
```
<codacy-jira-ticket>: Incorrect list-item indent

Solution:
Add 2 spaces 

Signed-off-by: hessio <patrick.hession@seagate.com>
```

**Review by mssawant — APPROVED** [review]
Minor comment regarding commit message, kindly address. No further reviews required.

**Comment by vaibhavparatwar** [comment]
@hessio please rebase your PR with latest main.. @SwapnilGaonkar7 @mssawant @Shreya-18 please review as you get chance.

**Comment by SwapnilGaonkar7** [comment]
`CORTX inclusive words scan / Alex report (pull_request) Failing after 35s — Alex report`
Should we fix it?

**Comment by hessio** [comment]
> `CORTX inclusive words scan / Alex report (pull_request) Failing after 35s — Alex report` Should we fix it?

Hi @SwapnilGaonkar7 this Alex issue is because the document is saying what should not be used in the CORTX project I did not add new text I am just fixing a formatting issue. The text that fails does not directly offend it is just saying how to avoid offending but Alex just looks for specific words and does not include the context they are in it appears. So I think that we don't need to fix this scan failure.

**Review by SwapnilGaonkar7 — APPROVED** [review]

**Review by Shreya-18 — APPROVED** [review]

**Comment by SwapnilGaonkar7** [comment]
@hessio There are 7 commits, please squash them

**Comment by mssawant** [comment]
@hessio, please address Alex failures.

**Comment by hessio** [comment]
> @hessio, please address Alex failures.

I did not change the wording of this PR I just changed the formatting to fix the codacy issue. The words are there to tell people what we don't allow in the community

**Comment by vaibhavparatwar** [comment]
@hessio please rebase/ update your branch with latest main..

**Comment by vaibhavparatwar** [comment]
@hessio  please reabase with latest main

**Comment by vaibhavparatwar** [comment]
@hessio  lets rebase with latest main and squash all commits. @mssawant  https://jts.seagate.com/browse/CORTX-32110 this issue will address Alex comments for this particular pr as per @mukul-seagate11 .

**Comment by vaibhavparatwar** [comment]
duplicate PR for #2107  ? @hessio ? if yes, lets close this one.

**Pull request closed without merging**
