### PR TITLE
CORTX-29982: [ordered-list-marker-value] Codacy issue

### PR DESCRIPTION
**Pull request by hessio**
Solution: Edit list numbering to increase by 1 instead of all elements labelled as 1

Signed-off-by: hessio <patrick.hession@seagate.com>

-----
[View rendered rfc/16/README.md](https://github.com/hessio/cortx-hare/blob/list-marker-value/rfc/16/README.md)

### CODE REVIEW

**Comment by vaibhavparatwar** [comment]
@hessio Please rebase your pr with latest main.. @mssawant @SwapnilGaonkar7 @Shreya-18 please review as you get chance

**Comment by hessio** [comment]
> @hessio Please rebase your pr with latest main.. @mssawant @SwapnilGaonkar7 @Shreya-18 please review as you get chance

rebased

**Comment by mssawant** [comment]
@hessio, please check `CORTX` inclusive words scan report.

**Comment by mssawant** [comment]
@hessio, please check Alex report failures.

**Comment by SwapnilGaonkar7** [comment]
@hessio Squash commits.

**Comment by hessio** [comment]
> @hessio, please check Alex report failures.

If you see Alex scan issues I did not change the content of the file this is just a formatting fix. I also don't think the words are used in an insensitive manner.

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Pull request merged**
