### PR TITLE
Fix file ownership after `sudo make install`

### PR DESCRIPTION
**Pull request by daniarherikurniawan**
I am following the readme and stumble upon this problem. When doing `sudo make install`, it will generate `vendor/` which is own by root (`drwxr-xr-x  4 root   root     44 Jun 22 16:23 vendor`).
Then, when we run `make rpm` for generating Hare RPMs, we will get this error: 
```sh
make[1]: Entering directory `/mnt/extra/hare'
ln: cannot remove ‘current’: Permission denied
make[1]: *** [unpack-dhall-bin] Error 1
make[1]: Leaving directory `/mnt/extra/hare'
make: *** [rpm] Error 2
```

Therefore, the simple fix is to apply chown to the `hare/`.

-----
[View rendered README.md](https://github.com/daniarherikurniawan/cortx-hare/blob/patch-3/README.md)

### CODE REVIEW

**Comment by knekrasov** [comment]
Not sure that this is worth documenting.
Normally, when the user runs something under `sudo`, it is expected that the files would be owned by the root user.

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by daniarherikurniawan** [comment]
@knekrasov , totally agree with you. However, my goal is to test that the Readme works without any errors. The thing is the error doesn't really tell you which dir caused the permission error, and anyone could easily waste 5 minutes to find the solution. 

There is another solution to this, which is to use `sudo` when running `make rpm`. Either way, I believe we still need to update the Readme.

**Comment by daniarherikurniawan** [comment]
Just to be clear, the readme tells us to use `sudo` when running `make install`. So, the Readme should also be accountable for causing the problem, thus it should provide a solution. Thanks.

**Comment by mukul-seagate11** [comment]
@gatekeepers, please review & merge the PR

**Comment by mukul-seagate11** [comment]
@suvratjoshi, @knekrasov, please review & merge the PR

**Review by knekrasov — APPROVED** [review]

**Comment by mukul-seagate11** [comment]
@Gatekeepers, please approve & merge the PR

**Review by suvratjoshi — APPROVED** [review]

**Comment by daniarherikurniawan** [comment]
Hi @knekrasov , @mssawant , @suvratjoshi; Could you merge this PR? Thanks

**Comment by suvratjoshi** [comment]
Hi @daniarherikurniawan
Can you please squash commits in a single and have the appropriate commit message for the same?
Thank you!

**Comment by daniarherikurniawan** [comment]
Hi @suvratjoshi! Sure, I will close this and create another PR

**Comment by daniarherikurniawan** [comment]
Hi @suvratjoshi , 
I am not sure what do you mean by "squash". I can't do that unless I make a new PR. Therefore, I have made a new PR here https://github.com/Seagate/cortx-hare/pull/1717, but it doesn't seem to be reviewed by the team. Please advise. Thanks :)

**Comment by daniarherikurniawan** [comment]
Hi Mandar @mssawant , could you please merge this. Thanks!

**Comment by vaibhavparatwar** [comment]
@mssawant @suvratjoshi  do we need this any more with latest dev environment? I am closing this right now, in  case required we can reopen

**Pull request closed without merging**
