### PR TITLE
EOS-15803 : Support: support bundle enhancements - Move /var/log/hare to /var/log/seagate/

### PR DESCRIPTION
**Pull request by supriyachavan4398**
Solution :
Redirect logs to Hare support bundle '/var/log/seagate/hare'.

Signed-off-by: Supriya Yadav <supriya.s.chavan@seagate.com>

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by supriyachavan4398** [comment]
Reviewer's @mssawant , @SwapnilGaonkar7 , @suvratjoshi , @knekrasov

**Comment by SwapnilGaonkar7** [comment]
Can you update what testing you have done after above changes

**Comment by supriyachavan4398** [comment]
> Can you update what testing you have done after above changes

Addressed and added all the results on [EOS-15803](https://jts.seagate.com/browse/EOS-15803)

**Comment by vaibhavparatwar** [comment]
1N VM deployment id working with custom build and also tested it.

http://eos-jenkins.colo.seagate.com/job/Cortx-Deployment/job/VM-Deployment-R2-1Node/1467/
{noformat}
[root@ssc-vm-6072 ~]# ls /var/log/seagate/hare/
consul-elect-rc-leader.log  consul-proto-rc.log  consul-watch-handler.log  setup.log
[root@ssc-vm-6072 ~]# ls -lrt /var/log/seagate/hare/
total 20
-rw-rwxr--+ 1 root root    54 Jul 13 07:30 consul-elect-rc-leader.log
-rw-rwxr--+ 1 root root     0 Jul 13 07:30 consul-proto-rc.log
-rw-rwxr--+ 1 root root   969 Jul 13 07:30 setup.log
-rw-rwxr--+ 1 root root 11987 Jul 13 07:41 consul-watch-handler.log
[root@ssc-vm-6072 ~]# salt '*' pillar.get release
srvnode-1:
    ----------
    target_build:
        http://cortx-storage.colo.seagate.com/releases/cortx/github/integration-custom-ci/centos-7.8.2003/custom-build-2108
    type:
        bundle
    update:
        ----------
        base_dir:
            /opt/seagate/cortx/updates
        repos:
            ----------
    upgrade:
        ----------
        base_dir:
            /opt/seagate/cortx/upgrades
        repos:
            ----------

{noformat}

**Comment by suvratjoshi** [comment]
@supriyachavan4398 
Looks like there are few more instances of /var/log/hare in the code which need to replaced.

**Comment by suvratjoshi** [comment]
Makefile
provisioning/miniprov/hare_mp/main.py --> logs_cleanup()
provisioning\miniprov\hare_mp\dhall\test.dhall
utils\elect-rc-leader - line 33
hare\utils\proto-rc

**Comment by supriyachavan4398** [comment]
> Makefile
> provisioning/miniprov/hare_mp/main.py --> logs_cleanup()
> provisioning\miniprov\hare_mp\dhall\test.dhall
> utils\elect-rc-leader - line 33
> hare\utils\proto-rc

Okay Sure, I'll check all the locations and change them.

**Comment by suvratjoshi** [comment]
These above given are just from my quick search in the code (my code is a little bit older)
So please check if these are valid and search through code please to ensure that we are covering all the instances correctly.

Test cases can be 
1. '/var/log/hare' directory is not created now
2. all the things that used to get collected in `/var/log/hare` should be found in `/var/log/seagate/hare'

**Comment by supriyachavan4398** [comment]
> These above given are just from my quick search in the code (my code is a little bit older)
> So please check if these are valid and search through code please to ensure that we are covering all the instances correctly.
> 
> Test cases can be
> 
> 1. '/var/log/hare' directory is not created now
> 2. all the things that used to get collected in `/var/log/hare` should be found in `/var/log/seagate/hare'

Addressed all the comments and done with changes.

**Comment by supriyachavan4398** [comment]
1N VM deployment id working with custom build and also tested it.

root@ssc-vm-6072 ~]# salt "*" state.apply components.hare
srvnode-1:
----------
          ID: Install cortx-hare
    Function: pkg.installed
        Name: cortx-hare
      Result: True
     Comment: 1 targeted package was installed/updated.
     Started: 03:27:47.463705
    Duration: 60241.864 ms
     Changes:
              ----------
              cortx-hare:
                  ----------
                  new:
                      2.0.0-2129_git08ef796.el7
                  old:
              cortx-motr:
                  ----------
                  new:
                      2.0.0-2129_gitf9697c7c_3.10.0_1127.el7
                  old:
                      2.0.0-2108_git46ec7dc5_3.10.0_1127.el7
----------
          ID: Stage - Post Install Hare
    Function: cmd.run
        Name: __slot__:salt:setup_conf.conf_cmd('/opt/seagate/cortx/hare/conf/setup.yaml', 'hare:post_install')
      Result: True
     Comment: Command "/opt/seagate/cortx/hare/bin/hare_setup post_install --config json:///opt/seagate/cortx_configs/provisioner_cluster.json --report-unavailable-features --configure-logrotate" run
     Started: 03:28:47.708995
    Duration: 4917.852 ms
     Changes:
              ----------
              pid:
                  55011
              retcode:
                  0
              stderr:
                  2021-07-15 09:28:52,435 [INFO] Server type (virtual)
                  2021-07-15 09:28:52,473 [INFO] GET http://127.0.0.1:9200/_nodes/_all/http [status:200 request:0.004s]
                  2021-07-15 09:28:52,477 [INFO] GET http://srvnode-1:9200/config/_alias?ignore_unavailable=true [status:200 request:0.003s]
                  2021-07-15 09:28:52,480 [INFO] GET http://srvnode-1:9200/config [status:200 request:0.003s]
                  2021-07-15 09:28:52,503 [INFO] PUT http://srvnode-1:9200/config/_doc/HARE%2FUNSUPPORTED_FEATURE%2FHCTL_NODE [status:200 request:0.021s]
                  2021-07-15 09:28:52,522 [INFO] POST http://srvnode-1:9200/config/_refresh [status:200 request:0.019s]
                  2021-07-15 09:28:52,524 [INFO] Server type (virtual)
              stdout:
----------
          ID: Stage - Prepare Hare
    Function: cmd.run
        Name: __slot__:salt:setup_conf.conf_cmd('/opt/seagate/cortx/hare/conf/setup.yaml', 'hare:prepare')
      Result: True
     Comment: Command "/opt/seagate/cortx/hare/bin/hare_setup prepare --config json:///opt/seagate/cortx_configs/provisioner_cluster.json" run
     Started: 03:28:52.627447
    Duration: 1667.552 ms
     Changes:
              ----------
              pid:
                  55165
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: Stage - Configure Hare
    Function: cmd.run
        Name: __slot__:salt:setup_conf.conf_cmd('/opt/seagate/cortx/hare/conf/setup.yaml', 'hare:config')
      Result: True
     Comment: Command "/opt/seagate/cortx/hare/bin/hare_setup config --config json:///opt/seagate/cortx_configs/provisioner_cluster.json --file '/var/lib/hare/cluster.yaml'" run
     Started: 03:28:54.295392
    Duration: 3493.748 ms
     Changes:
              ----------
              pid:
                  55214
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: Stage - Initialize Hare
    Function: cmd.run
        Name: __slot__:salt:setup_conf.conf_cmd('/opt/seagate/cortx/hare/conf/setup.yaml', 'hare:init')
      Result: True
     Comment: Command "/opt/seagate/cortx/hare/bin/hare_setup init --config json:///opt/seagate/cortx_configs/provisioner_cluster.json" run
     Started: 03:28:57.789562
    Duration: 87366.176 ms
     Changes:
              ----------
              pid:
                  55321
              retcode:
                  0
              stderr:
                  Cluster is not running

                  ?[1;33mWarning?[0m: Could not locate a cache base directory from the environment.

                  You can provide a cache base directory by pointing the $XDG_CACHE_HOME
                  environment variable to a directory with read and write permissions.


                  ?[1;33mWarning?[0m: Could not locate a cache base directory from the environment.

                  You can provide a cache base directory by pointing the $XDG_CACHE_HOME
                  environment variable to a directory with read and write permissions.

                  2021-07-15 09:29:59,944 [INFO] Waiting for all the processes to start..
                  2021-07-15 09:30:01,951 [INFO] Waiting for all the processes to start..
                  2021-07-15 09:30:03,959 [INFO] Waiting for all the processes to start..
                  Stopping s3server@0x7200000000000001:0x17 at ssc-vm-6072.colo.seagate.com...
                  Stopped s3server@0x7200000000000001:0x17 at ssc-vm-6072.colo.seagate.com
                  Stopping m0d@0x7200000000000001:0x9 (ios) at ssc-vm-6072.colo.seagate.com...
                  Stopped m0d@0x7200000000000001:0x9 (ios) at ssc-vm-6072.colo.seagate.com
                  Stopping m0d@0x7200000000000001:0x14 (confd) at ssc-vm-6072.colo.seagate.com...
                  Stopped m0d@0x7200000000000001:0x14 (confd) at ssc-vm-6072.colo.seagate.com
                  Stopping hare-hax at ssc-vm-6072.colo.seagate.com...
                  Stopped hare-hax at ssc-vm-6072.colo.seagate.com
                  Making sure that RC leader can be re-elected next time
                  Cluster is not running
              stdout:
                  2021-07-15 09:28:59: Generating cluster configuration... OK
                  2021-07-15 09:29:00: Stopping Consul on this node... OK
                  2021-07-15 09:29:12: Stopping Consul on other nodes... OK
                  2021-07-15 09:29:12: Starting Consul server on this node............. OK
                  2021-07-15 09:29:23: Importing configuration into the KV store... OK
                  2021-07-15 09:29:23: Starting Consul on other nodes... OK
                  2021-07-15 09:29:23: Updating Consul configuraton from the KV store... OK
                  2021-07-15 09:29:24: Waiting for the RC Leader to get elected.......... OK
                  2021-07-15 09:29:32: Starting Motr (phase1, mkfs)... OK
                  2021-07-15 09:29:40: Starting Motr (phase1, m0d)... OK
                  2021-07-15 09:29:43: Starting Motr (phase2, mkfs)... OK
                  2021-07-15 09:29:54: Starting Motr (phase2, m0d)... OK
                  2021-07-15 09:29:57: Starting S3 servers (phase3)... OK
                  2021-07-15 09:29:59: Checking health of services... OK
----------
          ID: Generate hare checkpoint flag
    Function: file.managed
        Name: /opt/seagate/cortx_configs/provisioner_generated/srvnode-1.hare
      Result: True
     Comment: Empty file
     Started: 03:30:25.173251
    Duration: 159.194 ms
     Changes:
              ----------
              new:
                  file /opt/seagate/cortx_configs/provisioner_generated/srvnode-1.hare created

Summary for srvnode-1
------------
Succeeded: 6 (changed=6)
Failed:    0
------------
Total states run:     6
Total run time: 157.846 s

[root@ssc-vm-6072 ~]# hctl status -d
Data pool:
    # fid name
    0x6f00000000000001:0x20 'storage-set-1__sns'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0x37 'Profile_the_pool': 'storage-set-1__sns' None None
Services:
    ssc-vm-6072.colo.seagate.com  (RC)
    [started]  hax        0x7200000000000001:0x6   192.168.90.242@tcp:12345:1:1
    [started]  ioservice  0x7200000000000001:0x9   192.168.90.242@tcp:12345:2:1
    [started]  confd      0x7200000000000001:0x14  192.168.90.242@tcp:12345:2:2
    [started]  s3server   0x7200000000000001:0x17  192.168.90.242@tcp:12345:3:1
    [unknown]  m0_client  0x7200000000000001:0x1a  192.168.90.242@tcp:12345:4:1
    [unknown]  m0_client  0x7200000000000001:0x1d  192.168.90.242@tcp:12345:4:2
Devices:
    ssc-vm-6072.colo.seagate.com
    [online]  /dev/null
    [online]  /dev/sdc


[root@ssc-vm-6072 ~]# ls /var/log/seagate/hare/
consul-elect-rc-leader.log  consul-proto-rc.log  consul-watch-handler.log  setup.log

**Review by mssawant — APPROVED** [review]

**Review by suvratjoshi — APPROVED** [review]

**Pull request merged**
