### PR TITLE
Create the hare group before adding user to it

### PR DESCRIPTION
**Pull request by daniarherikurniawan**
This is the solution to this issue https://github.com/Seagate/cortx-hare/issues/1659. There is another way to solve this, which is by adding this line to the makefile. Feel free to close this PR if the latter solution is preferable. Thanks!

-----
[View rendered README.md](https://github.com/daniarherikurniawan/cortx-hare/blob/patch-1/README.md)

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by daniarherikurniawan** [comment]
The team is working on this, so I will close it for now. Thanks!

**Comment by daniarherikurniawan** [comment]
@vaibhavparatwar @mssawant  I am reopening this PR since there is no other PR addressing this issue (https://github.com/Seagate/cortx-hare/issues/1659). My changes are in the README level, so it won't hurt any other dependent script. :)

**Comment by daniarherikurniawan** [comment]
Without this PR, we will get another error:
```sh
Error...blablablabla
Did you forget to add $USER to hare group?
```
when running `hctl bootstrap --mkfs CDF.yaml`. That is when you follow hare's README (https://github.com/Seagate/cortx-hare/blob/main/README.md#hare-we-go).

So, I believe this `hare` group creation is needed.

**Review by mssawant — APPROVED** [review]

**Pull request merged**
