### PR TITLE
CORTX-28870: Adding the allowable list for Alex scan

### PR DESCRIPTION
**Pull request by venkuppu-chn**
Signed-off-by: Venkatesh K <venkatesh.k@seagate.com>

### CODE REVIEW

**Comment by mssawant** [comment]
@venkuppu-chn , I couldn't understand the problem from any of the 3 commits. What is that we are trying to solve and adding here? Kindly elaborate the commit with a proper problem statement and the corresponding solution.

**Comment by venkuppu-chn** [comment]
> @venkuppu-chn , I couldn't understand the problem from any of the 3 commits. What is that we are trying to solve and adding here? Kindly elaborate the commit with a proper problem statement and the corresponding solution.

@mssawant 

Problem Statement
Alex scan generate false positive

Solution:
We have added some allowable list to ignore the false positives.

**Comment by mssawant** [comment]
@venkuppu-chn, I don't see any of the commit messages having the problem statement that you mentioned in your reply. We need the commit message to to be clear please. So kindly update the commit message accordingly.
Also if you could add some example around `Alex scan generate false positive`, it would be much better.
Thank you.

**Comment by venkuppu-chn** [comment]
> @venkuppu-chn, I don't see any of the commit messages having the problem statement that you mentioned in your reply. We need the commit message to to be clear please. So kindly update the commit message accordingly. Also if you could add some example around `Alex scan generate false positive`, it would be much better. Thank you.

@mssawant I have modified the commit message as per your suggestion. Kindly review and merge the PR.

**Comment by mssawant** [comment]
@venkuppu-chn , now I see 35 commits, please do not `git merge` but do `git rebase` with hare main. Kindly reset the head to your commit and rebase your branch with Hare main branch instead of main. The only commit that must be there is the one corresponding to this PR. Merging this as it is will just pollute the commit logs. cc @vaibhavparatwar

**Comment by venkuppu-chn** [comment]
@mssawant I have tried to rebase the branch, but I couldn't do it successfully.  

https://github.com/Seagate/cortx-hare/pull/2023

**Comment by venkuppu-chn** [comment]
> @venkuppu-chn , now I see 35 commits, please do not `git merge` but do `git rebase` with hare main. Kindly reset the head to your commit and rebase your branch with Hare main branch instead of main. The only commit that must be there is the one corresponding to this PR. Merging this as it is will just pollute the commit logs. cc @vaibhavparatwar

@mssawant I have tried to rebase the branch, but I couldn't do it successfully.  I'm closing this PR and created PR.

https://github.com/Seagate/cortx-hare/pull/2023

**Pull request closed without merging**
