### PR TITLE
README: update with transport_type config info

### PR DESCRIPTION
**Pull request by andriytk**
Update readme with the `transport_type` configuration information for libfabric.

-----
[View rendered README.md](https://github.com/andriytk/cortx-hare/blob/update-readme/README.md)

### CODE REVIEW

**Review by suvratjoshi — APPROVED** [review]

**Review by vaibhavparatwar — APPROVED** [review]

**Comment by vaibhavparatwar** [comment]
@mssawant  @suvratjoshi  can we merge this?

**Comment by suvratjoshi** [comment]
@andriytk 
Looks like there are three commits
Can you please make a single commit

**Comment by andriytk** [comment]
@suvratjoshi, you can use "Squash and merge" Github option when landing this PR and, while editing the final commit msg, leave only the one from the 1st commit in the resulting commit msg. Thanks.

**Comment by suvratjoshi** [comment]
> @suvratjoshi, you can use "Squash and merge" Github option when landing this PR and, while editing the final commit msg, leave only the one from the 1st commit in the resulting commit msg. Thanks.

Sorry @andriytk , currently I can not see any commit message for all the 3 commits

**Pull request merged**
