### PR TITLE
CORTX-33030: In Hare, Set default log level to INFO

### PR DESCRIPTION
**Pull request by pavankrishnat**
Problem:
As of now, much of the default logging in HARE is at DEBUG level. Its
recommended to use INFO as default log level, to generate just good enough logs
in production releases, and enable DEBUG log level only in development
systems. This enable system to more relevant logs in less number of lines and
hence size.

Solution:
Convert the DEBUG level of such logging to INFO level.

Signed-off-by: pavankrishnat <pavan.k.thunuguntla@seagate.com>

### CODE REVIEW

**Review by mssawant — APPROVED** [review]

**Review by Shreya-18 — APPROVED** [review]

**Comment by pavankrishnat** [comment]
retest this please

**Review by d-nayak — APPROVED** [review]

**Comment by d-nayak** [comment]
@pavankrishnat - Please post test results from this changeset.

**Comment by pavankrishnat** [comment]
> @pavankrishnat - Please post test results from this changeset.

@d-nayak - Manually deployed on 3N setup and did basic Happy Path testing, Successful.
Here are the Logs with & without Changes. http://cortx-storage.colo.seagate.com/logs1/3month-retention/CORTX-33030/

**Review by seagate-sarang-sawant — APPROVED** [review]

**Comment by pavankrishnat** [comment]
created new ticket to create new mechanism to separate INFO and Debug logs ( CORTX-34070 ).

**Comment by seagate-sarang-sawant** [comment]
Not all but some message which fits more with info level severity are converted from debug level to info.  Info level messages are still within the limits. Sanitizing logs messages will be taken in subsequent logging improvement stories.

**Pull request merged**
