### PR TITLE
CORTX-27923 - Upgrade aiohttp version to 3.8.1

### PR DESCRIPTION
**Pull request by swanand-gadre**
Problem:
aiohttp version is old. It needs to be upgraded

Solution:
aiohttp version will be upgraded to 3.8.1
This version is latest version and it is
expected to resolve security 
vulnerabilities.
Corresponding JIRA 
https://jts.seagate.com/browse/CORTX-27923
Detailed test results are documented and
document is attached to JIRA

### CODE REVIEW

**Comment by swanand-gadre** [comment]
**Please don't merge this PR directly.
As it has dependencies over multiple components
This PR will be merged in coordinated manner in a meeting by calling all component gatekeepers**

**Comment by vaibhavparatwar** [comment]
@mssawant  @SwapnilGaonkar7  - Was this PR discussed ?

**Review by SwapnilGaonkar7 — APPROVED** [review]

**Comment by SwapnilGaonkar7** [comment]
@swanand-gadre Have we tested this PR?
cc @vaibhavparatwar

**Comment by swanand-gadre** [comment]
> @mssawant @SwapnilGaonkar7 - Was this PR discussed ?

Hi @SwapnilGaonkar7 

Yes, testing is conducted on these changes.

Quick summary of testing done is as follows

- Completed successful build and deployment on 3+1 VM cortx k8s cluster
- Completed basic verification that aiohttp library is upgraded t 3.8.1 
  - inside cortx-rgw and cortx-all images
  - inside every contains in every pod created by the image
- Completed basic tests using AWS client, which includes, 
  -  bucket creation
  - uploading a large file into bucket
  - download the same file and validate md5sum

All the test results are uploaded in a document file. This document file is attached to the JIRA ticket -> https://jts.seagate.com/browse/CORTX-27923

Do let me know if any other concerns / queries.

Regards
Swanand

**Comment by swanand-gadre** [comment]
Please don't merge this PR directly.
As it has dependencies over multiple components
This PR will be merged in coordinated manner in a meeting by calling all component gatekeepers

**Review by vaibhavparatwar — APPROVED** [review]

**Comment by swanand-gadre** [comment]
Sure @mssawant 

Just to be clear, As I understand suggestions

- commit message should have description (like problem / solution that is present in the PR)
- Listing security vulnerability details (like CVE) in the description and in commit message.

Let me know if any gaps

I will follow these practices next time onwards

Regards
Swanand

**Pull request merged**
