### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kimika88**
null

-----
[View rendered README.md](https://github.com/kimika88/cortx-hare/blob/patch-1/README.md)

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by mssawant** [comment]
please elaborate the problem and solution in the commit message.

**Comment by vaibhavparatwar** [comment]
> @kimika88  could you please elaborate what is this PR for? Request you to add some description in commit message.

**Comment by kimika88** [comment]
> > @kimika88  could you please elaborate what is this PR for? Request you to add some description in commit message.

It's just that the instruction did not show "cd cortx-hare" that goes into the source code for hare for installation.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete

**Pull request closed without merging**
