### PR TITLE
EOS-27971:Problem: subsequent entrypoint requests are not received from motr

### PR DESCRIPTION
**Pull request by mssawant**
Hare, on receiving entrypoint request from a motr process fetches the
required information from Consul in-order to prepare the entrypoint
reply. If the required information is not available, Hare drops the
entrypoint requestsilently, expecting motr would timeout and resend
the entrypoint request. This mechanism was introduced to reduce the
number of entrypoint requests received from a motr process when Hare
replies with EAGAIN.

Solution:
Add a delay of 1 second before replying to entrypoint request in case
of a failure for now.

### CODE REVIEW

**Comment by vaibhavparatwar** [comment]
@mssawant  can we link it to any JIRA ID? and i see 1N deployment check is failing for this PR.

**Review by SwapnilGaonkar7 — APPROVED** [review]
Looks good.
I think we have already tested this approach.

**Comment by suvratjoshi** [comment]
retest this please

**Comment by suvratjoshi** [comment]
above comment was to auto trigger 1N deployment
no action needed from anybody

**Comment by mssawant** [comment]
@vaibhavparatwar, 1N deployment is passing now.

**Review by SwapnilGaonkar7 — APPROVED** [review]

**Comment by pragamj** [comment]
hctl status on 15
[hctl_status_15N.txt](https://github.com/Seagate/cortx-hare/files/8012919/hctl_status_15N.txt)
N

**Review by vaibhavparatwar — APPROVED** [review]

**Pull request merged**
