### PR TITLE
EOS-19065: Revert the feature temporarily

### PR DESCRIPTION
**Pull request by knekrasov**
Problem: this feature requires support from Motr side as well (in other
words, as of #1721 Hare assumes that Motr provides additional JSON
file). The feature is not fully implemented by Motr side,

Solution: revert the feature temporarily

### CODE REVIEW

**Review by vaibhavparatwar — APPROVED** [review]

**Review by SwapnilGaonkar7 — APPROVED** [review]

**Comment by SwapnilGaonkar7** [comment]
VM Deployment is failing, Is it expected?

**Comment by vaibhavparatwar** [comment]
Yes @SwapnilGaonkar7 deployment will fail.. as it has motr dependency

**Review by suvratjoshi — APPROVED** [review]

**Comment by vaibhavparatwar** [comment]
@knekrasov if this deployment job PASSes, we can close this PR without reverting the changes. 
http://eos-jenkins.colo.seagate.com/job/Cortx-Main/job/centos-7.8.2003/job/Partition%20Main%20Deploy%203N/177/

**Comment by vaibhavparatwar** [comment]
Closing this PR as no need to revert, because Motr has fixed the issue.

**Pull request closed without merging**
