### PR TITLE
EOS-24053: conf generation is impossible outside of hare-bootstrap

### PR DESCRIPTION
**Pull request by knekrasov**
Solution: Implement `configure` script that repeats the way how
hare-bootstrap script generates the configuration files.

Signed-off-by: Konstantin Nekrasov <konstantin.nekrasov@seagate.com>

### CODE REVIEW

**Comment by mssawant** [comment]
@knekrasov, can you change the base to kubernetes branch for now?  As this will not be required in main immediately for LR and we need to run some tests on this.
Also can you please post the output of its execution?

**Comment by knekrasov** [comment]
Here is the output of the command.

Help screen:
```
/opt/seagate/cortx/hare/bin/configure --help
Usage: configure [OPTIONS] CDF

  Generate Hare configuration according to the given CDF file.

  CDF   Full path to the Cluster Description File (CDF).

Options:
  -c, --conf-dir TEXT  Target folder where Hare-related configuration will be
                       written to.  [default: /var/lib/hare/]
  --help               Show this message and exit.
```

Config generation (I intentionally used artificial hostname defined through `/etc/salt/minion-id`, that's why there are several flavours of `hostname` command in the log):
```
 sudo /opt/seagate/cortx/hare/bin/configure ./cfgen/examples/einziel.yaml
2021-09-02 09:25:02,068 [DEBUG] Issuing command: ['cfgen', '-o', '/var/lib/hare/', './cfgen/examples/einziel.yaml']
2021-09-02 09:25:02,712 [DEBUG] Issuing command: ['cat', '/var/lib/hare//confd.dhall']
2021-09-02 09:25:02,714 [DEBUG] Issuing command: ['dhall', 'text']
2021-09-02 09:25:02,716 [DEBUG] Issuing command: ['m0confgen']
2021-09-02 09:25:03,080 [DEBUG] Issuing command: ['jq', '-r', '(.servers + .clients)[] | "\\(.node_name) \\(.ipaddr)"', '/var/lib/hare//consul-agents.json']
2021-09-02 09:25:03,126 [DEBUG] Issuing command: ['hostname']
2021-09-02 09:25:03,129 [DEBUG] Issuing command: ['hostname', '--fqdn']
2021-09-02 09:25:03,133 [DEBUG] Issuing command: ['hostname', '-I']
```

Files generated:
```
ls -lh /var/lib/hare/
total 56K
-rw-r--r-- 1 root root  14K Sep  2 09:25 confd.dhall
-rw-r--r-- 1 root root 5.3K Sep  2 09:25 confd.xc
-rw-r--r-- 1 root root  114 Sep  2 09:25 consul-agents.json
-rw-r--r-- 1 root root  187 Sep  2 09:25 consul-env
-rw-r--r-- 1 root root  13K Sep  2 09:25 consul-kv.json
drwxr-xr-x 2 root root 4.0K Sep  2 09:25 consul-server-conf
-rw-r--r-- 1 root root    6 Sep  2 09:25 node-name

```

**Comment by mssawant** [comment]
@knekrasov, make rpm is failing for some reason, checking from my side. Please check at your end too.
```

**Comment by mssawant** [comment]
+ /usr/lib/rpm/check-buildroot
/home/520478/rpmbuild/BUILDROOT/cortx-hare-2.0.0-1_git8762b47.el7.x86_64/opt/seagate/cortx/hare/bin/configure:sys.path.insert(1, '/home/520478/rpmbuild/BUILDROOT/cortx-hare-2.0.0-1_git8762b47.el7.x86_64/opt/seagate/cortx/hare/lib64/python3.6/site-packages') # Added by Makefile
/home/520478/rpmbuild/BUILDROOT/cortx-hare-2.0.0-1_git8762b47.el7.x86_64/opt/seagate/cortx/hare/bin/configure:sys.path.insert(2, '/home/520478/rpmbuild/BUILDROOT/cortx-hare-2.0.0-1_git8762b47.el7.x86_64/opt/seagate/cortx/hare/lib/python3.6/site-packages') # Added by Makefile
/home/520478/rpmbuild/BUILDROOT/cortx-hare-2.0.0-1_git8762b47.el7.x86_64/opt/seagate/cortx/hare/bin/hare_setup:sys.path.insert(1, '/home/520478/rpmbuild/BUILDROOT/cortx-hare-2.0.0-1_git8762b47.el7.x86_64/opt/seagate/cortx/hare/lib64/python3.6/site-packages') # Added by Makefile
/home/520478/rpmbuild/BUILDROOT/cortx-hare-2.0.0-1_git8762b47.el7.x86_64/opt/seagate/cortx/hare/bin/hare_setup:sys.path.insert(2, '/home/520478/rpmbuild/BUILDROOT/cortx-hare-2.0.0-1_git8762b47.el7.x86_64/opt/seagate/cortx/hare/lib/python3.6/site-packages') # Added by Makefile
Found '/home/520478/rpmbuild/BUILDROOT/cortx-hare-2.0.0-1_git8762b47.el7.x86_64' in installed files; aborting
error: Bad exit status from /var/tmp/rpm-tmp.fcck4X (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.fcck4X (%install)
make[1]: *** [__rpm] Error 1
make[1]: Leaving directory `/home/520478/cortx-hare-fork/cortx-hare-fork-new/cortx-hare-1'
make: *** [rpm] Error 2
```

**Comment by mssawant** [comment]
commenting out following lines worked, probably these should be in hare.spec in post_install section?
```
[520478@ssc-vm-3947:cortx-hare-1] git show
commit 4d89bfe31b57f3b4869e850572398861ae2ac732
Author: Mandar Sawant <mandar.sawant@seagate.com>
Date:   Sun Sep 5 14:19:04 2021 -0600

    comment fix_hare_imports.

diff --git a/Makefile b/Makefile
index 5d3ce5e..05aab88 100644
--- a/Makefile
+++ b/Makefile
@@ -638,13 +638,13 @@ define _log
     echo "$${YELLOW}    $(1)$${NC}"
 endef

-define _fix_hare_imports_ex
-    sed -i "7i sys.path.insert(1, '$(1)/lib64/python3.6/site-packages') # Added by Makefile" $(2) ;\
-    sed -i "8i sys.path.insert(2, '$(1)/lib/python3.6/site-packages') # Added by Makefile" $(2)
-endef
-
-define _fix_hare_imports
-    $(call _log,Fixing $(DESTDIR)/$(PREFIX)/bin/$(1)) ;\
-    $(call _fix_hare_imports_ex,$(DESTDIR)/$(PREFIX),$(DESTDIR)/$(PREFIX)/bin/$(1))
-endef
+# define _fix_hare_imports_ex
+#     sed -i "7i sys.path.insert(1, '$(1)/lib64/python3.6/site-packages') # Added by Makefile" $(2) ;\
+#     sed -i "8i sys.path.insert(2, '$(1)/lib/python3.6/site-packages') # Added by Makefile" $(2)
+# endef
+
+# define _fix_hare_imports
+#     $(call _log,Fixing $(DESTDIR)/$(PREFIX)/bin/$(1)) ;\
+#     $(call _fix_hare_imports_ex,$(DESTDIR)/$(PREFIX),$(DESTDIR)/$(PREFIX)/bin/$(1))
+# endef
 # vim: textwidth=80 nowrap foldmethod=marker
```

**Comment by knekrasov** [comment]
@mssawant I have fixed `make rpm`, thanks for pointing this out.

It took my a while to understand what the issue was. I was going to disable `check-buildroot` first but luckily I decided to read the script to understand what does it complain at. So the problem was in the fact that `$(DESTDIR)` was injected into the pythonic executables (which is fine when we run `make install` but totally wrong when we're building the RPM: the DESTDIR will point to a temporary chroot-folder).

**Comment by mssawant** [comment]
Tested the patch in the PR and looks good. Some additional things need to be done to invoke `configure`  utility from mini-provisioner to set the locale.
Another thing remains is to invoke `update-consul-conf`.
This PR is good to merge.

**Review by mssawant — APPROVED** [review]

**Review by vaibhavparatwar — APPROVED** [review]

**Pull request merged**
