### PR TITLE
CORTX-29741: replace obsolete conf-store keys

### PR DESCRIPTION
**Pull request by lakshita-jain**
keys replaced old to new:
cvg_count to num_cvg
storage_set_count to num_storage_set
Also changed: 
TMPL_CVG_COUNT TO TMPL_NUM_CVG
TMPL_STORAGESET_COUNT TO TMPL_NUM_STORAGESET
Signed-off-by: Lakshita Jain <lakshita.jain@seagate.com>

Signed-off-by: Lakshita Jain <lakshita.jain@seagate.com>

### CODE REVIEW

**Comment by cortx-admin** [comment]
Can one of the admins verify this patch?

**Comment by lakshita-jain** [comment]
3N deployment with this feature branch was successful https://eos-jenkins.colo.seagate.com/job/Provisioner/job/N-Node_CORTX_Deployment_on_K8s_Cluster/203/console

**Review by Shreya-18 — APPROVED** [review]

**Comment by pavankrishnat** [comment]
@mssawant started premerge test manually https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Component-Test/job/Hare-PreMerge-Test/1417/console

**Comment by pavankrishnat** [comment]
@mssawant,
PreMerge Test passed with changes in branch https://github.com/lakshita-jain/cortx-hare/tree/CORTX-29741 commitID#404f229f0c5311f2062a9df8373affd8b4899bf4
[Hare-PreMerge-Test#1417_console.log](https://github.com/Seagate/cortx-hare/files/8489641/Hare-PreMerge-Test.1417_console.log)

**Comment by mssawant** [comment]
somehow pre-merge tests from cicd are not completing, Hare team (@pavankrishnat) tried triggering pre-merge tests explicitly which completed successfully as mentioned above. Going ahead with merging.

**Pull request merged**
