### PR TITLE
EOS-21367 : Facter rpm doesn't exist

### PR DESCRIPTION
**Pull request by vaibhavparatwar**
Solution:
We replace facter with puppet agent

Signed-off-by: vaibhavparatwar <vaibhav.paratwar@seagate.com>

### CODE REVIEW

**Comment by vaibhavparatwar** [comment]
@andriytk @daniarherikurniawan  this PR will address issues faced by community for puppet-agent installation and requirements. cc @mssawant @knekrasov

**Review by johnbent — APPROVED** [review]

**Comment by daniarherikurniawan** [comment]
Thank you @vaibhavparatwar ! I will test out the patch.

**Review by mssawant — APPROVED** [review]

**Review by suvratjoshi — APPROVED** [review]

**Comment by daniarherikurniawan** [comment]
Hi @vaibhavparatwar,
I tested this patch on two different cloud providers and it works, but haven't fully solved the problem.
First of all, I want to confirm that the puppet agent is installed flawlessly with your method; and the `facter` at `/opt/puppetlabs/bin/facter` has version > 3.14 as required.

However, the servers (tested at Chameleon and Emulab) were not able to find the `puppet-agent`'s facter because the `hare.spec` failed to update the symlink. Currently, in the`hare.spec` there is this condition:
``` sh 
    if [[ ! -e /usr/bin/facter && -e /opt/puppetlabs/bin/facter ]] ; then
        ln -vsf /opt/puppetlabs/bin/facter /usr/bin/facter
```
In my servers, that condition is `false` because the first condition is not satisfied, thus the `facter` still points to the original facter (version 2.4.1)  instead of the `puppet-agent`'s facter (version 4.0.46).
Therefore, I am suggesting that we remove the ` ! -e /usr/bin/facter` checking and just have these instead:
``` sh 
    if [[ -e /opt/puppetlabs/bin/facter ]] ; then
        ln -vsf /opt/puppetlabs/bin/facter /usr/bin/facter
```

By doing so, it will always use puppet-agent's facter no matter what. This solution solved my problems on Emulab and Chameleon cloud. 
Note: the `facter` version 2.4.1 is installed automatically without me running any `facter` specific installation, I don't really investigate precisely when this facter got installed.

Please let me know if you have any questions. Thanks! 
cc: @mssawant @suvratjoshi

**Comment by vaibhavparatwar** [comment]
> Hi @vaibhavparatwar,
> I tested this patch on two different cloud providers and it works, but haven't fully solved the problem.
> First of all, I want to confirm that the puppet agent is installed flawlessly with your method; and the `facter` at `/opt/puppetlabs/bin/facter` has version > 3.14 as required.
> 
> However, the servers (tested at Chameleon and Emulab) were not able to find the `puppet-agent`'s facter because the `hare.spec` failed to update the symlink. Currently, in the`hare.spec` there is this condition:
> 
> ```shell
>     if [[ ! -e /usr/bin/facter && -e /opt/puppetlabs/bin/facter ]] ; then
>         ln -vsf /opt/puppetlabs/bin/facter /usr/bin/facter
> ```
> 
> In my servers, that condition is `false` because the first condition is not satisfied, thus the `facter` still points to the original facter (version 2.4.1) instead of the `puppet-agent`'s facter (version 4.0.46).
> Therefore, I am suggesting that we remove the ` ! -e /usr/bin/facter` checking and just have these instead:
> 
> ```shell
>     if [[ -e /opt/puppetlabs/bin/facter ]] ; then
>         ln -vsf /opt/puppetlabs/bin/facter /usr/bin/facter
> ```
> 
> By doing so, it will always use puppet-agent's facter no matter what. This solution solved my problems on Emulab and Chameleon cloud.
> Note: the `facter` version 2.4.1 is installed automatically without me running any `facter` specific installation, I don't really investigate precisely when this facter got installed.
> 
> Please let me know if you have any questions. Thanks!
> cc: @mssawant @suvratjoshi

@daniarherikurniawan  Thank you for your inputs. We will handle it in separate PR and this PR we will merge with current changes. cc @mssawant

**Pull request merged**
