### PR TITLE
CORTX-29199: DIX repair and rebalance in service types are missing

### PR DESCRIPTION
**Pull request by swapnil-seagate**
CORTX-29199: DIX repair and rebalance in service types are missing

It is observed that, on cluster, currently no DIX repair and rebalance services
are enabled even after adding DIX pool in the solutions.yaml or CDF file.
Same is observed using consul kv get command.
Because of this, whenever DIX repair or rebalance operations are triggered,
corresponding service fop types are missing as the respective services are
not registered. Thus, corresponding operation fails with and -EPROTO error.

Solution:
Enable DIX repair and rebalance service types in cfgen in-order to configure
the same during motr configuration.

Signed-off-by: ‘Swapnil <swapnil.chaudhary@seagate.com>

### CODE REVIEW

**Comment by mssawant** [comment]
@swapnil-seagate, kindly reword the commit message as,
```
CORTX-29199: DIX repair and rebalance in service types are missing

It is observed that, on cluster, currently no DIX repair and rebalance services
are enabled even after adding DIX pool in the solutions.yaml or CDF file.
Same is observed using consul kv get command.
Because of this, whenever DIX repair or rebalance operations are triggered,
corresponding service fop types are missing as the respective services are
not registered. Thus, corresponding operation fails with and -EPROTO error.

Solution:
Enable DIX repair and rebalance service types in cfgen in-order to configure
the same during motr configuration.

Signed-off-by: ‘Swapnil <swapnil.chaudhary@seagate.com>
```

**Review by mssawant — APPROVED** [review]
@swapnil-seagate, looks good, kindly update the commit message as specified. Thank you.

**Comment by vaibhavparatwar** [comment]
@swapnil-seagate  please add the logs from developer level testing as well.

**Review by vaibhavparatwar — APPROVED** [review]

**Comment by swapnil-seagate** [comment]
> @swapnil-seagate please add the logs from developer level testing as well.

I have commented the developer logs on JIRA.
Adding the same here.
Currently *DIX* service is not present in service type in cfgen file.
 Hence, when we check for DIX processes or services in consul kv, we get it as empty. Similarly confd.xc doesn't contain any entry for DIX.
```
[root@cortx-data-headless-svc-ssc-vm-rhev4-2416 /]# consul kv get -recurse | grep dix
m0conf/profiles/0x7000000000000001:0xd3:{"name": "Profile_the_pool", "pools": ["storage-set-1__sns", "storage-set-1__dix", null]}
[root@cortx-data-headless-svc-ssc-vm-rhev4-2416 /]#
```
But same is not the case with SNS.
 SNS repair and rebalance services are present in consul kv output.
```
[root@cortx-data-headless-svc-ssc-vm-rhev4-2416 /]# consul kv get -recurse | grep sns
m0conf/nodes/0x6e00000000000001:0x27/processes/0x7200000000000001:0x2e/services/0x7300000000000001:0x35:{"name": "sns_rep", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x27/processes/0x7200000000000001:0x2e/services/0x7300000000000001:0x36:{"name": "sns_reb", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x27/processes/0x7200000000000001:0x3b/services/0x7300000000000001:0x42:{"name": "sns_rep", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x27/processes/0x7200000000000001:0x3b/services/0x7300000000000001:0x43:{"name": "sns_reb", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x3/processes/0x7200000000000001:0x17/services/0x7300000000000001:0x1e:{"name": "sns_rep", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x3/processes/0x7200000000000001:0x17/services/0x7300000000000001:0x1f:{"name": "sns_reb", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x3/processes/0x7200000000000001:0xa/services/0x7300000000000001:0x11:{"name": "sns_rep", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x3/processes/0x7200000000000001:0xa/services/0x7300000000000001:0x12:{"name": "sns_reb", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x4b/processes/0x7200000000000001:0x52/services/0x7300000000000001:0x59:{"name": "sns_rep", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x4b/processes/0x7200000000000001:0x52/services/0x7300000000000001:0x5a:{"name": "sns_reb", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x4b/processes/0x7200000000000001:0x5f/services/0x7300000000000001:0x66:{"name": "sns_rep", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x4b/processes/0x7200000000000001:0x5f/services/0x7300000000000001:0x67:{"name": "sns_reb", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2416/processes/46/services/sns_reb:54
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2416/processes/46/services/sns_rep:53
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2416/processes/59/services/sns_reb:67
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2416/processes/59/services/sns_rep:66
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2417/processes/10/services/sns_reb:18
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2417/processes/10/services/sns_rep:17
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2417/processes/23/services/sns_reb:31
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2417/processes/23/services/sns_rep:30
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2418/processes/82/services/sns_reb:90
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2418/processes/82/services/sns_rep:89
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2418/processes/95/services/sns_reb:103
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2418/processes/95/services/sns_rep:102
m0conf/pools/0x6f00000000000001:0x93:storage-set-1__sns
m0conf/profiles/0x7000000000000001:0xd3:{"name": "Profile_the_pool", "pools": ["storage-set-1__sns", "storage-set-1__dix", null]}

```
With custom image created using changes pushed in PR-2053, we are able to get the DIX repair and rebalance services in consul kv output.
 Custom image
```
cortxcontrol: cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5723-custom-ci
    cortxdata: cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-5723-custom-ci
    cortxserver: cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-5723-custom-ci
    cortxha: cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5723-custom-ci
    cortxclient: cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5723-custom-ci
```
```
[root@cortx-data-headless-svc-ssc-vm-rhev4-2416 /]# consul kv get -recurse | grep dix
m0conf/nodes/0x6e00000000000001:0x2b/processes/0x7200000000000001:0x32/services/0x7300000000000001:0x3b:{"name": "dix_rep", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x2b/processes/0x7200000000000001:0x32/services/0x7300000000000001:0x3c:{"name": "dix_reb", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x2b/processes/0x7200000000000001:0x41/services/0x7300000000000001:0x4a:{"name": "dix_rep", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x2b/processes/0x7200000000000001:0x41/services/0x7300000000000001:0x4b:{"name": "dix_reb", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x3/processes/0x7200000000000001:0x19/services/0x7300000000000001:0x22:{"name": "dix_rep", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x3/processes/0x7200000000000001:0x19/services/0x7300000000000001:0x23:{"name": "dix_reb", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x3/processes/0x7200000000000001:0xa/services/0x7300000000000001:0x13:{"name": "dix_rep", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x3/processes/0x7200000000000001:0xa/services/0x7300000000000001:0x14:{"name": "dix_reb", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x53/processes/0x7200000000000001:0x5a/services/0x7300000000000001:0x63:{"name": "dix_rep", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x53/processes/0x7200000000000001:0x5a/services/0x7300000000000001:0x64:{"name": "dix_reb", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x53/processes/0x7200000000000001:0x69/services/0x7300000000000001:0x72:{"name": "dix_rep", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/0x6e00000000000001:0x53/processes/0x7200000000000001:0x69/services/0x7300000000000001:0x73:{"name": "dix_reb", "state": "M0_NC_UNKNOWN"}
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2416/processes/10/services/dix_reb:20
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2416/processes/10/services/dix_rep:19
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2416/processes/25/services/dix_reb:35
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2416/processes/25/services/dix_rep:34
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2417/processes/50/services/dix_reb:60
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2417/processes/50/services/dix_rep:59
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2417/processes/65/services/dix_reb:75
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2417/processes/65/services/dix_rep:74
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2418/processes/105/services/dix_reb:115
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2418/processes/105/services/dix_rep:114
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2418/processes/90/services/dix_reb:100
m0conf/nodes/cortx-data-headless-svc-ssc-vm-rhev4-2418/processes/90/services/dix_rep:99
m0conf/profiles/0x7000000000000001:0xdf:{"name": "Profile_the_pool", "pools": ["storage-set-1__sns", "storage-set-1__dix", null]}

```

The same is tested by sanjog and results are updated in CORTX-27964

**Comment by vaibhavparatwar** [comment]
@swapnil-seagate can you signoff PR ? also 1N K8s deployment failing, have you tested K8s deployment manually?

**Comment by swapnil-seagate** [comment]
> @swapnil-seagate can you signoff PR ? also 1N K8s deployment failing, have you tested K8s deployment manually?

Added the signoff and the results posted in above test are from 3N k8s set-up.
The deployment on 3N set-up was successful.

**Comment by vaibhavparatwar** [comment]
@SwapnilGaonkar7  Please review as you get chance and lets merge if all looks good.

**Comment by vaibhavparatwar** [comment]
@SwapnilGaonkar7 @mssawant premerge test is passing.. 1N deployment failing is a known and deployment was tested by @swapnil-seagate . Can we merge this PR?

**Comment by mssawant** [comment]
@swapnil-seagate, please update the commit message as suggested. cc @vaibhavparatwar

**Comment by swapnil-seagate** [comment]
> @swapnil-seagate, please update the commit message as suggested. cc @vaibhavparatwar

@mssawant , what is missing in the commit message ?
I copy-pasted the earlier one mentioned by you.

**Comment by vaibhavparatwar** [comment]
@SwapnilGaonkar7  @mssawant - can we merge this PR? is there something pending for this?

**Comment by mssawant** [comment]
@swapnil-seagate , I still see 3 commits and following commit message,
```
CORTX-29199: Add support for DIX repair and rebalance in service types
It is observed that, on cluster, currently no DIX repair and rebalance services are enabled even after adding DIX pool in the solutions.yaml or CDF file.
Same is observed using consul kv get command.
Because of this, whenever DIX repair or rebalance for is triggered, the motr-server is not able to lookup the respective opcode as those are not registered. Hence it returns protocol error (-EPROTO).

Solution:
The service types for DIX repair and rebalance need to be enabled in cfgen file.

Signed-off-by: ‘Swapnil <swapnil.chaudhary@seagate.com>
```
You have updated the description but not the commit message. Please also fixup the commits and update the commit message accordingly.

**Comment by mssawant** [comment]
@vaibhavparatwar, I do not see the updated commit message yet.

**Comment by swapnil-seagate** [comment]
> @vaibhavparatwar, I do not see the updated commit message yet.

Yes, I tried to amend the message, but it is failing every time.
Can gate-keeper update the message while merging the code ?

**Comment by vaibhavparatwar** [comment]
Closing this PR as PR #2056  is merged for this.

**Pull request closed without merging**
