### PR TITLE
Problem: Hare mini provisioner templates do not follow naming conventions

### PR DESCRIPTION
**Pull request by mssawant**
Solution:
Prefix all the variables from the templates with `TMPL` that need to be replaced
by the users.

Signed-off-by: Mandar Sawant <mandar.sawant@seagate.com>

### CODE REVIEW

**Review by knekrasov — COMMENTED** [review]
Please make 'test_template_sane' ignored. I believe it would fail.

**Review by knekrasov — APPROVED** [review]

**Comment by mssawant** [comment]
@knekrasov,
>Please make 'test_template_sane' ignored. I believe it would fail.

updated `provisioning/miniprov/create-template.sh`.

**Comment by knekrasov** [comment]
@mssawant Does this test work for you?
https://github.com/Seagate/cortx-hare/blob/main/provisioning/miniprov/test/test_cdf.py#L87-L98

Steps to reproduce:
0. activate python environment
1. cd provisioning/miniprov
2. python ./setup.py test

**Comment by mssawant** [comment]
@knekrasov , fixed working now,
```
(.py3venv) [520478@ssc-vm-1623:miniprov] python3.6 setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing hare_mp.egg-info/PKG-INFO
writing dependency_links to hare_mp.egg-info/dependency_links.txt
writing entry points to hare_mp.egg-info/entry_points.txt
writing requirements to hare_mp.egg-info/requires.txt
writing top-level names to hare_mp.egg-info/top_level.txt
reading manifest file 'hare_mp.egg-info/SOURCES.txt'
writing manifest file 'hare_mp.egg-info/SOURCES.txt'
running build_ext
test_invalid_machine_id (test.test_validator.TestValidator) ... ok
test_is_cluster_first_node (test.test_validator.TestValidator) ... ok
test_disk_refs_can_be_empty (test.test_cdf.TestCDF) ... ok
test_iface_type_can_be_null (test.test_cdf.TestCDF) ... ok
test_invalid_storage_set_configuration_rejected (test.test_cdf.TestCDF)
This test case checks whether exception will be raise if total ... ok
test_it_works (test.test_cdf.TestCDF) ... ok
test_metadata_is_hardcoded (test.test_cdf.TestCDF) ... ok
test_multiple_nodes_supported (test.test_cdf.TestCDF) ... ok
test_provided_values_respected (test.test_cdf.TestCDF) ... ok
test_template_sane (test.test_cdf.TestCDF) ... ok
test_disks_empty (test.test_cdf.TestTypes) ... ok
test_m0clients (test.test_cdf.TestTypes) ... ok
test_m0server_with_disks (test.test_cdf.TestTypes) ... ok
test_maybe_none (test.test_cdf.TestTypes) ... ok
test_pooldesc_empty (test.test_cdf.TestTypes) ... ok
test_protocol (test.test_cdf.TestTypes) ... ok

----------------------------------------------------------------------
Ran 16 tests in 0.238s

OK
```

**Review by SwapnilGaonkar7 — COMMENTED** [review]
Looks good

**Pull request merged**
