### PR TITLE
Merge dg_bytecount branch to main

### PR DESCRIPTION
**Pull request by Shreya-18**
Currently, deployment is failing due to missing changes (dg_bytecount) in Motr's main branch. 
Once Motr's `dg_bytecount` branch is merged to main, we can merge this PR.

Tests:

Deployment is successful with Motr's `dg_bytecount` branch.
link - https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/1133/

IOs are successful
```
[root@ssc-vm-g2-rhev4-2610 ~]# aws s3 mb s3://test-bucket --endpoint-url http://192.168.54.124:30080                                                     make_bucket: test-bucket
[root@ssc-vm-g2-rhev4-2610 ~]# aws s3 ls --endpoint-url http://192.168.54.124:30080
2022-03-21 02:28:31 test-bucket
[root@ssc-vm-g2-rhev4-2610 ~]#
[root@ssc-vm-g2-rhev4-2610 ~]# dd if=/dev/urandom of=/tmp/9M bs=1M count=9
9+0 records in
9+0 records out
9437184 bytes (9.4 MB) copied, 0.0800336 s, 118 MB/s
[root@ssc-vm-g2-rhev4-2610 ~]# dd if=/dev/urandom of=/tmp/8M bs=1M count=8
8+0 records in
8+0 records out
8388608 bytes (8.4 MB) copied, 0.0686868 s, 122 MB/s
[root@ssc-vm-g2-rhev4-2610 ~]# aws s3 cp /tmp/9M s3://test-bucket/object1 --endpoint-url http://192.168.54.124:30080
upload: ../tmp/9M to s3://test-bucket/object1
[root@ssc-vm-g2-rhev4-2610 ~]#
[root@ssc-vm-g2-rhev4-2610 ~]# aws s3 ls s3://test-bucket --endpoint-url http://192.168.54.124:30080
2022-03-21 02:29:46    9437184 object1
[root@ssc-vm-g2-rhev4-2610 ~]# aws s3 cp /tmp/9M s3://test-bucket/object2 --endpoint-url http://192.168.54.124:30080
upload: ../tmp/9M to s3://test-bucket/object2

[root@cortx-data-headless-svc-ssc-vm-g2-rhev4-2610 /]# hctl status
Bytecount:
    critical : 0
    damaged : 0
    degraded : 0
    healthy : 25165824
Data pool:
    # fid name
    0x6f00000000000001:0x93 'storage-set-1__sns'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0xd2 'Profile_the_pool': 'storage-set-1__sns' 'storage-set-1__dix' None
Services:
    cortx-data-headless-svc-ssc-vm-g2-rhev4-2611
    [started]  hax                 0x7200000000000001:0x2b         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2611@22001
    [started]  ioservice           0x7200000000000001:0x2e         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2611@21001
    [started]  ioservice           0x7200000000000001:0x3b         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2611@21002
    [started]  confd               0x7200000000000001:0x48         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2611@21003
    cortx-data-headless-svc-ssc-vm-g2-rhev4-2621  (RC)
    [started]  hax                 0x7200000000000001:0x7          inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2621@22001
    [started]  ioservice           0x7200000000000001:0xa          inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2621@21001
    [started]  ioservice           0x7200000000000001:0x17         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2621@21002
    [started]  confd               0x7200000000000001:0x24         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2621@21003
    cortx-data-headless-svc-ssc-vm-g2-rhev4-2610
    [started]  hax                 0x7200000000000001:0x4f         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2610@22001
    [started]  ioservice           0x7200000000000001:0x52         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2610@21001
    [started]  ioservice           0x7200000000000001:0x5f         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2610@21002
    [started]  confd               0x7200000000000001:0x6c         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2610@21003
    cortx-server-headless-svc-ssc-vm-g2-rhev4-2611
    [started]  hax                 0x7200000000000001:0x71         inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-2611@22001
    [started]  rgw                 0x7200000000000001:0x74         inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-2611@21501
    cortx-server-headless-svc-ssc-vm-g2-rhev4-2610
    [started]  hax                 0x7200000000000001:0x79         inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-2610@22001
    [started]  rgw                 0x7200000000000001:0x7c         inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-2610@21501
    cortx-server-headless-svc-ssc-vm-g2-rhev4-2621
    [started]  hax                 0x7200000000000001:0x81         inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-2621@22001
    [started]  rgw                 0x7200000000000001:0x84         inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-2621@21501

```

### CODE REVIEW

**Comment by vaibhavparatwar** [comment]
@mssawant  @SwapnilGaonkar7 please review this dg_bytecount merge to main. . @Shreya-18 we may need to rebase today.

**Comment by Shreya-18** [comment]
Deployment is success
https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/1270/

```
-----------------------------------[ Image Details ]--------------------------------------
ghcr.io/seagate/consul:1.10.0
cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-5421-custom-ci
cortx-docker.colo.seagate.com/seagate/cortx-rgw:2.0.0-5421-custom-ci
ghcr.io/seagate/kafka:3.0.0-debian-10-r7
ghcr.io/seagate/symas-openldap:2.4.58
ghcr.io/seagate/zookeeper:3.7.0-debian-10-r182
---------------------------------------[ POD Status ]--------------------------------------
NAME                                                 READY   STATUS    RESTARTS   AGE     IP               NODE                                    NOMINATED NODE   READINESS GATES
consul-client-267vs                                  1/1     Running   0          7m44s   172.18.189.42    ssc-vm-g2-rhev4-2621.colo.seagate.com              
consul-client-hm6nk                                  1/1     Running   0          8m11s   172.18.149.226   ssc-vm-g2-rhev4-2610.colo.seagate.com              
consul-client-n9rrh                                  1/1     Running   0          8m10s   172.18.251.187   ssc-vm-g2-rhev4-2611.colo.seagate.com              
consul-server-0                                      1/1     Running   0          6m30s   172.18.189.45    ssc-vm-g2-rhev4-2621.colo.seagate.com              
consul-server-1                                      1/1     Running   0          7m27s   172.18.251.183   ssc-vm-g2-rhev4-2611.colo.seagate.com              
consul-server-2                                      1/1     Running   0          8m15s   172.18.149.222   ssc-vm-g2-rhev4-2610.colo.seagate.com              
cortx-control-9799b4f78-v5ss9                        1/1     Running   0          5m      172.18.189.17    ssc-vm-g2-rhev4-2621.colo.seagate.com              
cortx-data-ssc-vm-g2-rhev4-2610-6677f8d48d-qqv65     4/4     Running   0          4m1s    172.18.149.223   ssc-vm-g2-rhev4-2610.colo.seagate.com              
cortx-data-ssc-vm-g2-rhev4-2611-5c697fbcb7-5d8hm     4/4     Running   0          4m1s    172.18.251.179   ssc-vm-g2-rhev4-2611.colo.seagate.com              
cortx-data-ssc-vm-g2-rhev4-2621-6f47484c5b-rx6fx     4/4     Running   0          4m      172.18.189.23    ssc-vm-g2-rhev4-2621.colo.seagate.com              
cortx-ha-5cdc7b465b-8g8n9                            3/3     Running   0          44s     172.18.251.146   ssc-vm-g2-rhev4-2611.colo.seagate.com              
cortx-server-ssc-vm-g2-rhev4-2610-655f4b7b98-vtfg7   2/2     Running   0          2m12s   172.18.149.204   ssc-vm-g2-rhev4-2610.colo.seagate.com              
cortx-server-ssc-vm-g2-rhev4-2611-6699448c76-qqstg   2/2     Running   0          2m12s   172.18.251.185   ssc-vm-g2-rhev4-2611.colo.seagate.com              
cortx-server-ssc-vm-g2-rhev4-2621-7d5db74844-8tf85   2/2     Running   0          2m11s   172.18.189.43    ssc-vm-g2-rhev4-2621.colo.seagate.com              
kafka-0                                              1/1     Running   0          6m7s    172.18.189.24    ssc-vm-g2-rhev4-2621.colo.seagate.com              
kafka-1                                              1/1     Running   0          6m7s    172.18.251.155   ssc-vm-g2-rhev4-2611.colo.seagate.com              
kafka-2                                              1/1     Running   0          6m7s    172.18.149.233   ssc-vm-g2-rhev4-2610.colo.seagate.com              
openldap-0                                           1/1     Running   0          8m15s   172.18.149.220   ssc-vm-g2-rhev4-2610.colo.seagate.com              
openldap-1                                           1/1     Running   0          8m      172.18.251.182   ssc-vm-g2-rhev4-2611.colo.seagate.com              
openldap-2                                           1/1     Running   0          7m36s   172.18.189.44    ssc-vm-g2-rhev4-2621.colo.seagate.com              
zookeeper-0                                          1/1     Running   0          6m59s   172.18.189.47    ssc-vm-g2-rhev4-2621.colo.seagate.com              
zookeeper-1                                          1/1     Running   0          6m59s   172.18.251.153   ssc-vm-g2-rhev4-2611.colo.seagate.com              
zookeeper-2                                          1/1     Running   0          6m59s   172.18.149.230   ssc-vm-g2-rhev4-2610.colo.seagate.com              
-----------[ Sleeping for 1min before checking hctl status.... ]--------------------
---------------------------------------[ hctl status ]-----------------------------------------
Tue Mar 22 03:18:13 MDT 2022
Bytecount:
    critical : 0
    damaged : 0
    degraded : 0
    healthy : 0
Data pool:
    # fid name
    0x6f00000000000001:0x93 'storage-set-1__sns'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0xd2 'Profile_the_pool': 'storage-set-1__sns' 'storage-set-1__dix' None
Services:
    cortx-data-headless-svc-ssc-vm-g2-rhev4-2621 
    [started]  hax                 0x7200000000000001:0x2b         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2621@22001
    [started]  ioservice           0x7200000000000001:0x2e         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2621@21001
    [started]  ioservice           0x7200000000000001:0x3b         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2621@21002
    [started]  confd               0x7200000000000001:0x48         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2621@21003
    cortx-data-headless-svc-ssc-vm-g2-rhev4-2611  (RC)
    [started]  hax                 0x7200000000000001:0x7          inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2611@22001
    [started]  ioservice           0x7200000000000001:0xa          inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2611@21001
    [started]  ioservice           0x7200000000000001:0x17         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2611@21002
    [started]  confd               0x7200000000000001:0x24         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2611@21003
    cortx-data-headless-svc-ssc-vm-g2-rhev4-2610 
    [started]  hax                 0x7200000000000001:0x4f         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2610@22001
    [started]  ioservice           0x7200000000000001:0x52         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2610@21001
    [started]  ioservice           0x7200000000000001:0x5f         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2610@21002
    [started]  confd               0x7200000000000001:0x6c         inet:tcp:cortx-data-headless-svc-ssc-vm-g2-rhev4-2610@21003
    cortx-server-headless-svc-ssc-vm-g2-rhev4-2611 
    [started]  hax                 0x7200000000000001:0x71         inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-2611@22001
    [started]  rgw                 0x7200000000000001:0x74         inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-2611@21501
    cortx-server-headless-svc-ssc-vm-g2-rhev4-2610 
    [started]  hax                 0x7200000000000001:0x79         inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-2610@22001
    [started]  rgw                 0x7200000000000001:0x7c         inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-2610@21501
    cortx-server-headless-svc-ssc-vm-g2-rhev4-2621 
    [started]  hax                 0x7200000000000001:0x81         inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-2621@22001
    [started]  rgw                 0x7200000000000001:0x84         inet:tcp:cortx-server-headless-svc-ssc-vm-g2-rhev4-2621@21501
-----------[ Time taken for service to start 0 mins ]--------------------
```

**Review by vaibhavparatwar — APPROVED** [review]

**Comment by vaibhavparatwar** [comment]
@SwapnilGaonkar7 @mssawant Lets review and merge this dg_bytecount feature branch to main asap. cc @Shreya-18

**Review by mssawant — APPROVED** [review]

**Review by SwapnilGaonkar7 — APPROVED** [review]

**Comment by vaibhavparatwar** [comment]
@SwapnilGaonkar7 @Shreya-18  now all is green for this PR to merge.. can we push it?

**Pull request merged**
