### PR TITLE
WhiteSource Local config file

### PR DESCRIPTION
**Pull request by mukul-seagate11**
**Problem: <the problem that your commit solves>**

WhiteSource Local config file will be created to scan & detect vulnerabilities based on local component configurations/Artifacts/code extensions etc.

### CODE REVIEW

**Comment by knekrasov** [comment]
@mukul-seagate11 Can you describe what problem does your patch solve? PR description doesn't state it.

Commit message doesn't look informative: `Add files via upload`
Please consider form `Problem: <problem that this commit resolves>` instead.

Thank you!

**Comment by mukul-seagate11** [comment]
> @mukul-seagate11 Can you describe what problem does your patch solve? PR description doesn't state it.
> 
> Commit message doesn't look informative: `Add files via upload`
> Please consider form `Problem: <problem that this commit resolves>` instead.
> 
> Thank you!

@knekrasov, All gatekeepers are already notified that WhiteSource will be integrated for repos which will scan the code for any vulnerabilities, you can refer more in EOS-22003

**Comment by knekrasov** [comment]
@mukul-seagate11 it would be nice if you put this context into PR description (including the link to the ticket if it helps to understand why exactly this PR is needed).

Please squash the commits and use `Problem: <the problem that your commit solves>` format for commit message. 

Thank you in advance.

**Comment by mukul-seagate11** [comment]
> @mukul-seagate11 it would be nice if you put this context into PR description (including the link to the ticket if it helps to understand why exactly this PR is needed).
> 
> Please squash the commits and use `Problem: <the problem that your commit solves>` format for commit message.
> 
> Thank you in advance.

Done

**Comment by mssawant** [comment]
@mukul-seagate11 , the commit messages does not make any sense,
```
Add files via upload

@mukul-seagate11
mukul-seagate11 committed 5 days ago
  
Add files via upload 

Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
@mukul-seagate11
mukul-seagate11 committed 4 days ago
 
Merge branch 'mukul-seagate11-patch-4' of https://github.com/Seagate/… 

…cortx-hare into mukul-seagate11-patch-4

Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
@mukul-seagate11
mukul-seagate11 committed 4 days ago
```

>@knekrasov, All gatekeepers are already notified that WhiteSource will be integrated for repos which will scan the code for any vulnerabilities, you can refer more in EOS-22003

I believe community does not have access to Jira. It does not suffice to just update the PR, kindly please squash/fixup the commits and update the commit message as per the PR description.
It should be possible to infer the code changes looking at the commit message. The commit messages need to be elaborate. Thank you.

**Comment by mukul-seagate11** [comment]
Will raise another PR updating the description

**Pull request closed without merging**
