### PR TITLE
Update Codacy Badge

### PR DESCRIPTION
**Pull request by hessio**
Resolves [issue #1528](https://github.com/Seagate/cortx/issues/1528)

Signed-off-by: hessio <patrick.hession@seagate.com>

Signed-off-by: Patrick Hession <patrick.hession@seagate.com>

-----
[View rendered README.md](https://github.com/Seagate/cortx-hare/blob/hessio-patch-1/README.md)

### CODE REVIEW

**Review by d-nayak — APPROVED** [review]

**Review by vaibhavparatwar — APPROVED** [review]

**Comment by mssawant** [comment]
@hessio, can you elaborate a more about the problem and the fix? why codacy badge was wrong and how this PR fixes it?

**Comment by hessio** [comment]
> @hessio, can you elaborate a more about the problem and the fix? why codacy badge was wrong and how this PR fixes it?

Yes sure I can elaborate - Codacy Badge is not rendering correctly on the HARE README - see below:



I updated the Codacy Badge link from the Codacy app to fix the error.

**Comment by mssawant** [comment]
Thanks @hessio, in general it is good practice to have a clear commit message to understand the problem and the fix. It is evident that codacy badge was not rendering but it is good to elaborate why the badge stopped rendering or was it not rendering from the start itself. And what was actually missing and how we fixed this problem. Was there some update to the badge and do we need to look into this periodically or was it that we missed something from our side.

**Comment by hessio** [comment]
> Thanks @hessio, in general it is good practice to have a clear commit message to understand the problem and the fix. It is evident that codacy badge was not rendering but it is good to elaborate why the badge stopped rendering or was it not rendering from the start itself. And what was actually missing and how we fixed this problem. Was there some update to the badge and do we need to look into this periodically or was it that we missed something from our side.

I am not sure what caused the issue - to fix the issue I just went to the Codacy dashboard and copy/pasted the link to the Codacy Badge for this repo.

**Comment by hessio** [comment]
@mssawant can we merge this PR?

**Review by pavankrishnat — APPROVED** [review]

**Pull request merged**
