### PR TITLE
README: update

### PR DESCRIPTION
**Pull request by andriytk**
Get rid of the Welcome section in the beginning which is confusing and not longer true, I'm afraid.

### CODE REVIEW

**Comment by andriytk** [comment]
cc @chumakd, @vvv

**Review by azheregelya — APPROVED** [review]

**Review by knekrasov — APPROVED** [review]
Farewell, old good times

**Comment by andriytk** [comment]
"old good times" of social experiments? :)

**Comment by knekrasov** [comment]
Yes, the times when we had such an opportunity. No jokes, it's been a marvelous time and the results we got then prove that simply.

Some real benefits of those approaches are only being evaluated and understood by our dev team (including me). 

@vvv I didn't always understand your ideas and trade-offs, but now I can compare 😄 you were often right.

**Pull request merged**
