### PR TITLE
[GitHub Action] Issue triage

### PR DESCRIPTION
**Pull request by gauravchaudhari02**
Signed-off-by: Gaurav Chaudhari <gaurav.chaudhari@seagate.com>

## Why Triage?
Triage is an important part of open source. It can be difficult to keep up with the issues as the size of a project grows, the demands placed on the maintainers grow. This means they are forced to choose between spending enormous amounts of time reviewing each GitHub issue, only skimming over issues, or worse, ignoring issues.

## How triage action would be helpful?
Triage action can help an open-source project by labeling newly opened issues as `needs-triage`. So, maintainers could easily filter out all unattended/missed issues and label them appropriately in triage meetings. Now, it would be easy for a specific group of maintainers to filter out issues of their expertise/interest and start reviewing it in a timely manner.

### CODE REVIEW

**Review by mukul-seagate11 — APPROVED** [review]
looks good

**Review by shailesh-vaidya — APPROVED** [review]

**Comment by knekrasov** [comment]
@gauravchaudhari02 Sorry, I'm a kind of ignorant of github actions. I understand that your patch will just add the action from [here](https://github.com/Logerfo/triage-action) to cortx-hare repository.

But what will it change in our workflow?
Will this action just add "needs-triage" label to all new issues?

**Comment by gauravchaudhari02** [comment]
> @gauravchaudhari02 Sorry, I'm a kind of ignorant of github actions. I understand that your patch will just add the action from [here](https://github.com/Logerfo/triage-action) to cortx-hare repository.
> 
> But what will it change in our workflow?
> Will this action just add "needs-triage" label to all new issues?

👋🏼 @knekrasov, Yes. This action will add a `needs-triage` label to the issue on creation. So, you could label appropriate labels to all `needs-triage` labeled issues in issue-triage meetings or on issue creation itself and remove the `needs-triage` label.

**Review by knekrasov — APPROVED** [review]

**Comment by gauravchaudhari02** [comment]
👋🏼 @knekrasov, could you please merge it?

**Comment by knekrasov** [comment]
@gauravchaudhari02 I'm a kind of disenfranchised 😄 I don't have such a button.

@chumakd  or @mssawant Can you hit the button please?

**Pull request merged**
