### PR TITLE
Fault tolerance rebase for fixing DCO issue

### PR DESCRIPTION
**Pull request by SwapnilGaonkar7**
Tested bootstrap with 3 node
[root@ssc-vm-g2-rhev4-0199 ~]# hctl status
Data pool:
    # fid name
    0x6f00000000000001:0x8d 'storage-set-1__sns'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0xef 'Profile_the_pool': 'storage-set-1__sns' 'storage-set-1__dix' None
Services:
    srvnode-1.data.private
    [started]  hax        0x7200000000000001:0x7   192.168.82.1@tcp:12345:1:1
    [started]  ioservice  0x7200000000000001:0xa   192.168.82.1@tcp:12345:2:1
    [started]  ioservice  0x7200000000000001:0x19  192.168.82.1@tcp:12345:2:2
    [started]  confd      0x7200000000000001:0x28  192.168.82.1@tcp:12345:2:3
    [unknown]  m0_client  0x7200000000000001:0x2b  192.168.82.1@tcp:12345:4:1
    [unknown]  m0_client  0x7200000000000001:0x2e  192.168.82.1@tcp:12345:4:2
    srvnode-2.data.private
    [started]  hax        0x7200000000000001:0x35  192.168.82.17@tcp:12345:1:1
    [started]  ioservice  0x7200000000000001:0x38  192.168.82.17@tcp:12345:2:1
    [started]  ioservice  0x7200000000000001:0x47  192.168.82.17@tcp:12345:2:2
    [started]  confd      0x7200000000000001:0x56  192.168.82.17@tcp:12345:2:3
    [unknown]  m0_client  0x7200000000000001:0x59  192.168.82.17@tcp:12345:4:1
    [unknown]  m0_client  0x7200000000000001:0x5c  192.168.82.17@tcp:12345:4:2
    srvnode-3.data.private  (RC)
    [started]  hax        0x7200000000000001:0x63  192.168.82.4@tcp:12345:1:1
    [started]  ioservice  0x7200000000000001:0x66  192.168.82.4@tcp:12345:2:1
    [started]  ioservice  0x7200000000000001:0x75  192.168.82.4@tcp:12345:2:2
    [started]  confd      0x7200000000000001:0x84  192.168.82.4@tcp:12345:2:3
    [unknown]  m0_client  0x7200000000000001:0x87  192.168.82.4@tcp:12345:4:1
    [unknown]  m0_client  0x7200000000000001:0x8a  192.168.82.4@tcp:12345:4:2

Tested degraded IO by writing and reading before and after node shutdown.
`diff  /tmp/read_before_node_fail_fault_tol_rebase /tmp/read_after_node_fail_fault_tol_rebase`

Files are same.

### CODE REVIEW

**Review by vaibhavparatwar — APPROVED** [review]

**Comment by vaibhavparatwar** [comment]
@SwapnilGaonkar7  there are some codacy issues.

**Comment by SwapnilGaonkar7** [comment]
@vaibhavparatwar I think we can ignore them.
Anyway we are not adding new code here, just changing author of 1 commit.

**Comment by vaibhavparatwar** [comment]
> @vaibhavparatwar I think we can ignore them.
> Anyway we are not adding new code here, just changing author of 1 commit.

Ok

**Review by suvratjoshi — APPROVED** [review]

**Comment by vaibhavparatwar** [comment]
If this PR is not required, can we close it? @mssawant @SwapnilGaonkar7

**Comment by SwapnilGaonkar7** [comment]
Approach taken in this PR will not fix issue in target branch.
So closing this PR

**Pull request closed without merging**
