### PR TITLE
CORTX-31595 : Exclude CODE_OF_CONDUCT file from Alex Scan

### PR DESCRIPTION
**Pull request by subhalaxmisa**
Exclude CODE_OF_CONDUCT file from Alex Scan

Signed-off-by: subhalaxmisa <subhalaxmi.sahoo@seagate.com>

### CODE REVIEW

**Review by mssawant — APPROVED** [review]

**Review by vaibhavparatwar — APPROVED** [review]

**Review by d-nayak — APPROVED** [review]

**Comment by vaibhavparatwar** [comment]
retest this please

**Review by seagate-sarang-sawant — APPROVED** [review]

**Comment by seagate-sarang-sawant** [comment]
retest this please

**Comment by seagate-sarang-sawant** [comment]
@subhalaxmisa  Can you raise another PR without merge commits.  Use rebase and have a single commit.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete

**Pull request closed without merging**
