### PR TITLE
Merge main->stable 09/01/21

### PR DESCRIPTION
**Pull request by knekrasov**
null

-----
[View rendered README.md](https://github.com/knekrasov/cortx-hare/blob/main-stable-0901/README.md)
[View rendered ha-simulator/README.md](https://github.com/knekrasov/cortx-hare/blob/main-stable-0901/ha-simulator/README.md)

### CODE REVIEW

**Review by vaibhavparatwar — APPROVED** [review]

**Comment by mssawant** [comment]
Looks like VM deployments are failing but hare does not seem to be a reason.

**Comment by mssawant** [comment]
Looks like VM deployments are failing but Hare doesn't looks like a reason for the failure.

**Comment by mssawant** [comment]
@vaibhavparatwar , Can we find out the reason and try to deploy a custom build just to make sure if everything is working fine from our side?

**Review by mssawant — APPROVED** [review]

**Comment by vaibhavparatwar** [comment]
> @vaibhavparatwar , Can we find out the reason and try to deploy a custom build just to make sure if everything is working fine from our side?

We may not be able to test with current stable branch of motr as we want motr's changes in stable first for VM deployment to pass. Lets see if motr can merge their changes and then we can create custom build and test

**Pull request merged**
