### PR TITLE
EOS-26855: Fix Hare cfgen tests

### PR DESCRIPTION
**Pull request by pavankrishnat**
**Problem:**
Hare's `make cfgen` tests are failing.

**Solution:**
Need modifications in cfgen, sample files and corresponding dhall
files to fix the tests.

Signed-off-by: pavankrishnat <pavan.k.thunuguntla@seagate.com>

### CODE REVIEW

**Comment by SwapnilGaonkar7** [comment]
@pavankrishnat Can you post output of commands(which were failing earlier) after fix?

**Comment by pavankrishnat** [comment]
@SwapnilGaonkar7, Error before fix
```
(.py3venv) [root@ssc-vm-g3-rhev4-2546 cfgen]# make check
flake8  cfgen
set -eu -o pipefail; for f in cfgen; do MYPYPATH=../stubs:../hax mypy --config-file ../hax/mypy.ini  $f; done
Success: no issues found in 1 source file
set -eu -o pipefail;\
 out=$(mktemp -d);\
 ./cfgen -D ./dhall --mock --debug examples/singlenode.yaml >/dev/null;\
 ./cfgen -D ./dhall --mock -o $out examples/singlenode.yaml;\
 dhall text <$out/confd.dhall | m0confgen >/dev/null;\
 jq . <$out/consul-kv.json >/dev/null;\
 rm -r $out
for cdf in examples/*.yaml; do\
 yaml-to-dhall ./dhall/types/ClusterDesc.dhall <$cdf >/dev/null; done
yaml-to-dhall ./dhall/types/ClusterDesc.dhall <examples/singlenode.yaml\
 | dhall-to-yaml | diff -u - <(dhall-to-yaml <<<./tests/singlenode.dhall)


↳ ./tests/singlenode.dhall

Prelude : { Bool :
              { and : List Bool → Bool
              , build : (Type → _ → _@1 → _@2) → Bool
              , even : List Bool → Bool
              , fold : Bool → Type → _ → _@1 → _@2
              , not : Bool → Bool
              , odd : List Bool → Bool
              , or : List Bool → Bool
              , show : Bool → Text
              }
          , Double : { show : Double → Text }
          , Function :
              { compose : Type → Type → Type → (_@2 → _@2) → (_@2 → _@2) → _@4 → _@3 }
          , Integer : { show : Integer → Text, toDouble : Integer → Double }
          , JSON :
              { Nesting : Type
              , Tagged : Type → Type
              , Type : Type
              , array :
                    List
          ============================================================================
                            → _@1
                        , text : Text → _@1
                        }
                      → _@1
                    )
                  → Text
              , text :
                    Text
                  → Type
                  → { element :
                          { attributes : List { mapKey : Text, mapValue : Text }
                          , content : List _
                          , name : Text
                          }
                        → _@1
                    , text : Text → _@1
                    }
                  → _@1
              }
          }
types : { Addr : Type
        , ClusterDesc : Type
        , Controller : Type
        , Disk : Type
        , DiskRef : Type
        , Drive : Type
        , Enclosure : Type
        , Endpoint : Type
        , FailVec : Type
        , FdmiFilter : Type
        , FdmiFilterDesc : Type
        , FdmiFltGrp : Type
        , LibfabricEndpoint : Type
        , LnetEndpoint : Type
        , M0ServerDesc : Type
        , NetFamily : Type
        , NetId : Type
        , Node : Type
        , NodeDesc : Type
        , Obj : Type
        , ObjT : Type
        , Objv : Type
        , Oid : Type
        , Pool : Type
        , PoolDesc : Type
        , PoolType : Type
        , PoolsRef : Type
        , Process : Type
        , Profile : Type
        , Protocol : Type
        , Pver : Type
        , PverF : Type
        , Rack : Type
        , Root : Type
        , Sdev : Type
        , Service : Type
        , Site : Type
        , SvcT : Type
        }

Error: Expression doesn't match annotation

{ nodes : …
          { - data_iface_ip_addr : …
          , - memorysize_mb : …
          , - processorcount : …
          , - transport_type : …
          ,   m0_servers : …
                           ( …
                             { io_disks : { data : …
                                                   - { … : … }
                                                   + Text
                                          , …
                                          }
                             , …
                             }
                           )
          ,   machine_id : - Optional …
                           + Text
          , …
          }
, …
}

25│ { create_aux = Some False
26│ , nodes =
27│     [ { hostname = "localhost"
28│       , machine_id = "123hjbdf"
29│       , data_iface = "eth1"
30│       , data_iface_type = None types.Protocol
31│       , m0_servers =
32│           Some
33│           [ { runs_confd = Some True
34│             , io_disks =
35│                 { meta_data = None Text
36│                 , data = [] : List Text
37│                 }
38│             }
39│           , { runs_confd = None Bool
40│             , io_disks =
41│                 { meta_data = None Text
42│                 , data =
43│                     let mkPath = \(i : Natural) -> "/dev/loop" ++ Natural/show i
44│                     in Prelude.List.generate 10 Text mkPath
====================================================================================
58│           [ { node = Some "localhost", path = "/dev/loop0" }
59│           , { node = Some "localhost", path = "/dev/loop1" }
60│           , { node = Some "localhost", path = "/dev/loop2" }
61│           , { node = Some "localhost", path = "/dev/loop3" }
62│           , { node = Some "localhost", path = "/dev/loop4" }
63│           , { node = Some "localhost", path = "/dev/loop5" }
64│           , { node = Some "localhost", path = "/dev/loop6" }
65│           , { node = Some "localhost", path = "/dev/loop7" }
66│           , { node = Some "localhost", path = "/dev/loop8" }
67│           , { node = Some "localhost", path = "/dev/loop9" }
68│           ]
69│       , data_units = 1
70│       , parity_units = 0
71│       , spare_units = Some 0
72│       , allowed_failures = None types.FailVec
73│       }
74│     ]
75│ , profiles = None (List types.PoolsRef)
76│ , fdmi_filters = None (List types.FdmiFilterDesc)
77│ } : types.ClusterDesc

/root/Mainhare/cfgen/tests/singlenode.dhall:25:1

1│ ./tests/singlenode.dhall

(stdin):1:1
--- -   2022-01-21 06:34:58.837932924 -0700
+++ /dev/fd/63  2022-01-21 06:34:58.830242728 -0700
@@ -1,82 +0,0 @@
-pools:
-- allowed_failures: null
-  spare_units: 0
-  name: the pool
-  data_units: 1
-  parity_units: 0
-  disk_refs:
-  - path: /dev/loop0
-    node: localhost
-  - path: /dev/loop1
-    node: localhost
-  - path: /dev/loop2
-    node: localhost
-  - path: /dev/loop3
-    node: localhost
-  - path: /dev/loop4
-    node: localhost
-  - path: /dev/loop5
-    node: localhost
-  - path: /dev/loop6
-    node: localhost
-  - path: /dev/loop7
-    node: localhost
-  - path: /dev/loop8
-    node: localhost
-  - path: /dev/loop9
-    node: localhost
-  type: sns
-create_aux: false
-profiles: null
-fdmi_filters: null
-nodes:
-- transport_type: libfab
-  m0_servers:
-  - io_disks:
-      data: []
-      meta_data: null
-    runs_confd: true
-  - io_disks:
-      data:
-      - path: /dev/loop0
-        size: null
-        blksize: null
-      - path: /dev/loop1
-        size: null
-        blksize: null
-      - path: /dev/loop2
-        size: null
-        blksize: null
-      - path: /dev/loop3
-        size: null
-        blksize: null
-      - path: /dev/loop4
-        size: null
-        blksize: null
-      - path: /dev/loop5
-        size: null
-        blksize: null
-      - path: /dev/loop6
-        size: null
-        blksize: null
-      - path: /dev/loop7
-        size: null
-        blksize: null
-      - path: /dev/loop8
-        size: null
-        blksize: null
-      - path: /dev/loop9
-        size: null
-        blksize: null
-      meta_data: null
-    runs_confd: null
-  data_iface: eth1
-  hostname: localhost
-  data_iface_ip_addr: null
-  m0_clients:
-    other: 2
-    s3: 0
-  memorysize_mb: null
-  machine_id: null
-  processorcount: null
-  data_iface_type: null
make: *** [check-dhall] Error 1
```

**Comment by pavankrishnat** [comment]
@SwapnilGaonkar7, Below output after fix
```
(.py3venv) [root@ssc-vm-g3-rhev4-2546 cfgen]# make check
flake8  cfgen
set -eu -o pipefail; for f in cfgen; do MYPYPATH=../stubs:../hax mypy --config-file ../hax/mypy.ini  $f; done
Success: no issues found in 1 source file
set -eu -o pipefail;\
 out=$(mktemp -d);\
 ./cfgen -D ./dhall --mock --debug examples/singlenode.yaml >/dev/null;\
 ./cfgen -D ./dhall --mock -o $out examples/singlenode.yaml;\
 dhall text <$out/confd.dhall | m0confgen >/dev/null;\
 jq . <$out/consul-kv.json >/dev/null;\
 rm -r $out
for cdf in examples/*.yaml; do\
 yaml-to-dhall ./dhall/types/ClusterDesc.dhall <$cdf >/dev/null; done
yaml-to-dhall ./dhall/types/ClusterDesc.dhall <examples/singlenode.yaml\
 | dhall-to-yaml | diff -u - <(dhall-to-yaml <<<./tests/singlenode.dhall)
xcode() { sort | m0confgen; };\
 dhall text --file tests/sample-confd.dhall | xcode\
 | diff -u - <(xcode <tests/conf.cg)
(.py3venv) [root@ssc-vm-g3-rhev4-2546 cfgen]#
```

**Comment by mssawant** [comment]
@pavankrishnat, from commit message I am not understanding what was the problem, can you please elaborate a bit?

**Review by mssawant — APPROVED** [review]

**Comment by suvratjoshi** [comment]
Hi @pavankrishnat 
Looks like the commit message is empty.

**Comment by suvratjoshi** [comment]
@pavankrishnat 

Title :
> EOS-26855: Fix Hare tests on kubernetes branch

We dont have kubernetes branch.

Title can be modified to :
```
EOS-26855: Fix Hare cfgen tests
```

Description :
> Problem:
> Hare Pre-Merge Jenkins Job are failing at unit Test stage.
> 
> Solution:
> By correcting the dhall and yaml files "cfgen - make check" is working.

This test failure is not specific to premerge tests

Description can be modified to :
```
Problem:
Hare's `make cfgen` tests are failing.

Solution:
Need modifications in cfgen, sample file files and corresponding dhall
files to fix the tests.
```

**Comment by pavankrishnat** [comment]
> @pavankrishnat
> 
> Title :
> 
> > EOS-26855: Fix Hare tests on kubernetes branch
> 
> We dont have kubernetes branch.
> 
> Title can be modified to :
> 
> ```
> EOS-26855: Fix Hare cfgen tests
> ```
> 
> Description :
> 
> > Problem:
> > Hare Pre-Merge Jenkins Job are failing at unit Test stage.
> > Solution:
> > By correcting the dhall and yaml files "cfgen - make check" is working.
> 
> This test failure is not specific to premerge tests
> 
> Description can be modified to :
> 
> ```
> Problem:
> Hare's `make cfgen` tests are failing.
> 
> Solution:
> Need modifications in cfgen, sample files and corresponding dhall
> files to fix the tests.
> ```

Updated both commit message and PR title

**Comment by suvratjoshi** [comment]
@pavankrishnat 
Is the PR rebased with latest main branch

**Comment by pavankrishnat** [comment]
> @pavankrishnat Is the PR rebased with latest main branch

No

**Comment by pavankrishnat** [comment]
rebased with latest main branch
```
cortx-hare_new (EOS26855)
$ git log --oneline
80068e0 (HEAD -> EOS26855, origin/EOS26855) EOS-26855: Fix Hare cfgen tests
e8b0182 (upstream/main, main) EOS-27016: device info accessed before saving
384194b provisioning: mini provisioning unit tests are failing
1ac85e4 (upstream/rgw) EOS-27301: find and fix all URLs in hare code
```

**Review by SwapnilGaonkar7 — APPROVED** [review]

**Review by suvratjoshi — APPROVED** [review]

**Pull request merged**
