### PR TITLE
Problem: Durability keys are changed to include pool type(currently hardcoded to 'sns')

### PR DESCRIPTION
**Pull request by SwapnilGaonkar7**
Solution: Modified keys to include pool type(sns)

### CODE REVIEW

**Review by s-arya — APPROVED** [review]

**Comment by suvratjoshi** [comment]
Do we need changes in `provisioning\miniprov\test\test_cdf.py` ?

**Review by knekrasov — CHANGES_REQUESTED** [review]
Automatic tests fail, as @suvratjoshi suspected:

```
03:26:45 | BR handle_pooltype  .../hare/provisioning/miniprov  python ./setup.py build
running build
running build_py
copying test/test_cdf.py -> build/lib/test
copying hare_mp/main.py -> build/lib/hare_mp
copying hare_mp/store.py -> build/lib/hare_mp
copying hare_mp/types.py -> build/lib/hare_mp
copying hare_mp/cdf.py -> build/lib/hare_mp
copying hare_mp/dhall/gencdf.dhall -> build/lib/hare_mp/dhall
 03:26:53 | BR handle_pooltype  .../hare/provisioning/miniprov  python ./setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing hare_mp.egg-info/PKG-INFO
writing dependency_links to hare_mp.egg-info/dependency_links.txt
writing entry points to hare_mp.egg-info/entry_points.txt
writing requirements to hare_mp.egg-info/requires.txt
writing top-level names to hare_mp.egg-info/top_level.txt
reading manifest file 'hare_mp.egg-info/SOURCES.txt'
writing manifest file 'hare_mp.egg-info/SOURCES.txt'
running build_ext
test_invalid_machine_id (test.test_validator.TestValidator) ... ok
test_is_cluster_first_node (test.test_validator.TestValidator) ... ok
test_disk_refs_can_be_empty (test.test_cdf.TestCDF) ... ERROR
test_iface_type_can_be_null (test.test_cdf.TestCDF) ... ok
test_invalid_storage_set_configuration_rejected (test.test_cdf.TestCDF)
This test case checks whether exception will be raise if total ... ERROR
test_it_works (test.test_cdf.TestCDF) ... ERROR
test_metadata_is_hardcoded (test.test_cdf.TestCDF) ... ok
test_multiple_nodes_supported (test.test_cdf.TestCDF) ... ok
test_provided_values_respected (test.test_cdf.TestCDF) ... ERROR
test_template_sane (test.test_cdf.TestCDF) ... ok
test_disks_empty (test.test_cdf.TestTypes) ... ok
test_m0clients (test.test_cdf.TestTypes) ... ok
test_m0server_with_disks (test.test_cdf.TestTypes) ... ok
test_maybe_none (test.test_cdf.TestTypes) ... ok
test_pooldesc_empty (test.test_cdf.TestTypes) ... ok
test_protocol (test.test_cdf.TestTypes) ... ok

======================================================================
ERROR: test_disk_refs_can_be_empty (test.test_cdf.TestCDF)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/projects/hare/provisioning/miniprov/test/test_cdf.py", line 206, in test_disk_refs_can_be_empty
    ret = CdfGenerator(provider=store).generate()
  File "/mnt/projects/hare/provisioning/miniprov/hare_mp/cdf.py", line 129, in generate
    gencdf = self._get_cdf_dhall()
  File "/mnt/projects/hare/provisioning/miniprov/hare_mp/cdf.py", line 117, in _get_cdf_dhall
    pools = self._create_pool_descriptions()
  File "/mnt/projects/hare/provisioning/miniprov/hare_mp/cdf.py", line 69, in _create_pool_descriptions
    f'cluster>{cluster_id}>storage_set[{x}]>durability>sns>data'))
  File "/mnt/projects/hare/provisioning/miniprov/hare_mp/store.py", line 27, in get
    ret = self._raw_get(key)
  File "/usr/lib64/python3.6/unittest/mock.py", line 939, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib64/python3.6/unittest/mock.py", line 1005, in _mock_call
    result = effect(*args, **kwargs)
  File "/mnt/projects/hare/provisioning/miniprov/test/test_cdf.py", line 203, in ret_values
    return data[value]
KeyError: 'cluster>CLUSTER_ID>storage_set[0]>durability>sns>data'

======================================================================
ERROR: test_invalid_storage_set_configuration_rejected (test.test_cdf.TestCDF)
This test case checks whether exception will be raise if total
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/projects/hare/provisioning/miniprov/test/test_cdf.py", line 242, in test_invalid_storage_set_configuration_rejected
    CdfGenerator(provider=store)._create_pool_descriptions()
  File "/mnt/projects/hare/provisioning/miniprov/hare_mp/cdf.py", line 69, in _create_pool_descriptions
    f'cluster>{cluster_id}>storage_set[{x}]>durability>sns>data'))
  File "/mnt/projects/hare/provisioning/miniprov/hare_mp/store.py", line 27, in get
    ret = self._raw_get(key)
  File "/usr/lib64/python3.6/unittest/mock.py", line 939, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib64/python3.6/unittest/mock.py", line 1005, in _mock_call
    result = effect(*args, **kwargs)
  File "/mnt/projects/hare/provisioning/miniprov/test/test_cdf.py", line 237, in ret_values
    return data[value]
KeyError: 'cluster>CLUSTER_ID>storage_set[0]>durability>sns>data'

======================================================================
ERROR: test_it_works (test.test_cdf.TestCDF)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/projects/hare/provisioning/miniprov/test/test_cdf.py", line 127, in test_it_works
    CdfGenerator(provider=store).generate()
  File "/mnt/projects/hare/provisioning/miniprov/hare_mp/cdf.py", line 129, in generate
    gencdf = self._get_cdf_dhall()
  File "/mnt/projects/hare/provisioning/miniprov/hare_mp/cdf.py", line 117, in _get_cdf_dhall
    pools = self._create_pool_descriptions()
  File "/mnt/projects/hare/provisioning/miniprov/hare_mp/cdf.py", line 69, in _create_pool_descriptions
    f'cluster>{cluster_id}>storage_set[{x}]>durability>sns>data'))
  File "/mnt/projects/hare/provisioning/miniprov/hare_mp/store.py", line 27, in get
    ret = self._raw_get(key)
  File "/usr/lib64/python3.6/unittest/mock.py", line 939, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib64/python3.6/unittest/mock.py", line 1005, in _mock_call
    result = effect(*args, **kwargs)
  File "/mnt/projects/hare/provisioning/miniprov/test/test_cdf.py", line 123, in ret_values
    return data[value]
KeyError: 'cluster>CLUSTER_ID>storage_set[0]>durability>sns>data'

======================================================================
ERROR: test_provided_values_respected (test.test_cdf.TestCDF)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/projects/hare/provisioning/miniprov/test/test_cdf.py", line 163, in test_provided_values_respected
    ret = CdfGenerator(provider=store)._create_pool_descriptions()
  File "/mnt/projects/hare/provisioning/miniprov/hare_mp/cdf.py", line 69, in _create_pool_descriptions
    f'cluster>{cluster_id}>storage_set[{x}]>durability>sns>data'))
  File "/mnt/projects/hare/provisioning/miniprov/hare_mp/store.py", line 27, in get
    ret = self._raw_get(key)
  File "/usr/lib64/python3.6/unittest/mock.py", line 939, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib64/python3.6/unittest/mock.py", line 1005, in _mock_call
    result = effect(*args, **kwargs)
  File "/mnt/projects/hare/provisioning/miniprov/test/test_cdf.py", line 152, in ret_values
    return data[value]
KeyError: 'cluster>CLUSTER_ID>storage_set[0]>durability>sns>data'

----------------------------------------------------------------------
Ran 16 tests in 0.136s

FAILED (errors=4)
Test failed: <unittest.runner.TextTestResult run=16 errors=4 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=16 errors=4 failures=0>
```

@s-arya this will not break the build (since this kind of tests is not executed by default). Suggestion:
1. Merge this patch
2. Ask @SwapnilGaonkar7 to prepare follow-up PR that fixes these tests.

Thoughts?

**Comment by SwapnilGaonkar7** [comment]
@suvratjoshi  @knekrasov Addressed your review comments. Please have a look

**Review by knekrasov — APPROVED** [review]
Tests pass. Looks good!

**Pull request merged**
