### PR TITLE
Added steps to install cortx-utils

### PR DESCRIPTION
**Pull request by hessio**
Signed-off-by: Patrick Hession <patrick.hession@seagate.com>

Steps to install py-utils are essential to be able to `make` and `make install` HARE.

-----
[View rendered README.md](https://github.com/hessio/cortx-hare/blob/patch-5/README.md)

### CODE REVIEW

**Comment by suvratjoshi** [comment]
I think if we merge : https://github.com/Seagate/cortx-hare/pull/1595/files, we will not need these changes.
Right @knekrasov ?

**Comment by knekrasov** [comment]
Yes, seems like it is a duplicate of #1595

**Comment by suvratjoshi** [comment]
@hessio ,
Thank you for this patch but looks like the mentioned one already suffices the need.
We can close this patch if #1595 fulfills the need already.
Please confirm.

Thanks!

**Comment by hessio** [comment]
Oh you are right thanks, I will close this, when will this patch be merged to main?

**Comment by hessio** [comment]
Oh you are right thanks, I will close this, when will this patch be merged to main? resolved in #1595

**Comment by suvratjoshi** [comment]
I think today its possible as there are approvals.
cc: @knekrasov

**Pull request closed without merging**
