### PR TITLE
EOS-15799 Management: display cluster configuration

### PR DESCRIPTION
**Pull request by SwapnilGaonkar7**
Modified code to get list of devices and status.
Code will read entries from KV present in the below format "m0conf/nodes/<node_id>/processes/<process_fidk>/services/<svc_fid>/sdevs/<sdev_fid>"

### CODE REVIEW

**Comment by SwapnilGaonkar7** [comment]
@knekrasov @mssawant @chumakd @s-arya Please have a look

**Review by chumakd — APPROVED** [review]

**Comment by knekrasov** [comment]
@SwapnilGaonkar7 please squash your commits and use the proper github account please. The commits don't look very good:
image

**Comment by SwapnilGaonkar7** [comment]
@knekrasov Please have a look.

**Review by knekrasov — APPROVED** [review]
Looks good!

**Pull request merged**
