### PR TITLE
CORTX-29871: process state machine update multiple times

### PR DESCRIPTION
**Pull request by mssawant**
Process events are a broadcast to all the nodes in the cluster.
Not all the nodes are required to update the entire process configuration
tree in KV. Only the process's local hax or RC must do that.

Solution:
- Avoid updating process configuration tree in KV, but notify local motr
processes about any remote process state updates.
- Set HA and Confd process states to M0_CONF_HA_PROCESS_RECOVERED
on receiving M0_CONF_HA_PROCESS_STARTED.

Signed-off-by: Mandar Sawant <mandar.sawant@seagate.com>

### CODE REVIEW

**Comment by mssawant** [comment]
retest this please

**Comment by mssawant** [comment]
retest this please

**Comment by vaibhavparatwar** [comment]
@mssawant what is the JIRA Id to link with this PR?

**Comment by mssawant** [comment]
retest this please

**Review by Shreya-18 — APPROVED** [review]

**Comment by supriyachavan4398** [comment]
With Mandar's branch, tried to do bootstrap in LR env,
```
[root@ssc-vm-g2-rhev4-1947 cortx-hare-1]# hctl bootstrap --mkfs ~/1n_new.yaml
2022-08-16 01:06:16: Generating cluster configuration... OK
2022-08-16 01:06:17: Starting Consul server on this node......... OK
2022-08-16 01:06:24: Importing configuration into the KV store... OK
2022-08-16 01:06:24: Starting Consul on other nodes...Consul ready on all nodes
2022-08-16 01:06:25: Updating Consul configuration from the KV store... OK
2022-08-16 01:06:26: Waiting for the RC Leader to get elected....... OK
2022-08-16 01:06:31: Starting Motr (phase1, mkfs)... OK
2022-08-16 01:06:38: Starting Motr (phase1, m0d)... OK
2022-08-16 01:06:40: Starting Motr (phase2, mkfs)...Job for motr-mkfs@0x7200000000000001:0x2.service failed because the control process exited with error code. See "systemctl status motr-mkfs@0x7200000000000001:0x2.service" and "journalctl -xe" for details.
[root@ssc-vm-g2-rhev4-1947 cortx-hare-1]# hctl status
Bytecount:
    critical : 0
    damaged : 0
    degraded : 0
    healthy : 0
Data pool:
    # fid name
    0x6f00000000000001:0x0 'the pool'
Profile:
    # fid name: pool(s)
    0x7000000000000001:0x0 'default': 'the pool' None None
Services:
    ssc-vm-g2-rhev4-1947.colo.seagate.com  (RC)
    [started]  hax                 0x7200000000000001:0x0          inet:tcp:192.168.62.178@22001
    [started]  confd               0x7200000000000001:0x1          inet:tcp:192.168.62.178@21002
    [offline]  ioservice           0x7200000000000001:0x2          inet:tcp:192.168.62.178@21003
    [unknown]  m0_client_other     0x7200000000000001:0x3          inet:tcp:192.168.62.178@22501
    [unknown]  m0_client_other     0x7200000000000001:0x4          inet:tcp:192.168.62.178@22502
```
But it was failing to start ioservices.
cc. @mssawant, @vaibhavparatwar

**Comment by nkommuri** [comment]
Created a custom build [ https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/7556/ ] with this PR and motr PR https://github.com/Seagate/cortx-motr/pull/2078

Tested this build on my 9 node cluster. After cluster shutdown and restart, I see all device's state to be online immediately. Didn't see the issue of device state fluctuation.

**Review by vaibhavparatwar — APPROVED** [review]

**Review by d-nayak — APPROVED** [review]

**Pull request merged**
